//! Provider model catalogs, generated rather than hand-maintained.
//!
//! Every hand-written window in this project drifted, and each drift produced
//! the same bug: the context gauge reads high and auto-compaction fires early,
//! because the runtime divides by a number nobody re-checked after the vendor
//! changed it. Sonnet 4.6 sat at 200k while serving 1M; the GPT-5.4+ line sat
//! at 272k while serving 1.05M.
//!
//! SOURCES, in descending order of authority (all fetched 2026-07-29):
//!
//!   1. THE PROVIDER\'S OWN METADATA — venice, chutes, deepinfra, huggingface
//!      publish context length (and Venice publishes `supportsReasoningEffort`
//!      outright) on their public `/models`. Nothing beats the server telling
//!      you what it serves.
//!   2. THE PROVIDER\'S ID LIST + a resolved match — nvidia and ollama-cloud
//!      return ids and nothing else, so capabilities come from matching the
//!      same underlying model in the aggregator catalog.
//!   3. THE AGGREGATOR\'S SERVED NUMBERS — openai, anthropic, google, xai, meta.
//!      No API key is held for these, so the figure is what the aggregator
//!      measures serving the identical model. A measurement, not a press release.
//!   4. CURATED IDS, REFRESHED — key-gated providers (groq, mistral, together,
//!      fireworks, moonshot, zai, cerebras, ...) 401/403 without a key, so their
//!      model LIST stays curated while windows and capabilities are refreshed
//!      from a resolved match.
//!
//! `verified` is false where no source covered the model and the row carries
//! its curated or family-default value. Those rows stay listed — a real id the
//! picker can offer beats hiding it — but nothing may present them as fact.

/// `(id, display name, context window, reasoning, takes reasoning_effort, tool calling, verified)`
pub type CatalogRow = (&'static str, &'static str, u32, bool, bool, bool, bool);

/// anthropic: 17 models (0 unverified).
pub static ANTHROPIC_MODELS: &[CatalogRow] = &[
    (
        "claude-3-haiku",
        "Claude 3 Haiku",
        200000,
        false,
        false,
        true,
        true,
    ),
    (
        "claude-fable-5",
        "Claude Fable 5",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-haiku-4.5",
        "Claude Haiku 4.5",
        200000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-4",
        "Claude Opus 4",
        200000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-4.1",
        "Claude Opus 4.1",
        200000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-4.5",
        "Claude Opus 4.5",
        200000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-4.6",
        "Claude Opus 4.6",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-opus-4.7",
        "Claude Opus 4.7",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-opus-4.7-fast",
        "Claude Opus 4.7 (Fast)",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-opus-4.8",
        "Claude Opus 4.8",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-opus-4.8-fast",
        "Claude Opus 4.8 (Fast)",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-opus-5",
        "Claude Opus 5",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-opus-5-fast",
        "Claude Opus 5 (Fast)",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-sonnet-4",
        "Claude Sonnet 4",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-sonnet-4.5",
        "Claude Sonnet 4.5",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-sonnet-4.6",
        "Claude Sonnet 4.6",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-sonnet-5",
        "Claude Sonnet 5",
        1000000,
        true,
        true,
        true,
        true,
    ),
];

/// byteplus: 3 models (3 unverified).
pub static BYTEPLUS_MODELS: &[CatalogRow] = &[
    (
        "glm-4-7-251222",
        "GLM 4.7",
        200000,
        false,
        false,
        true,
        false,
    ),
    (
        "kimi-k2-5-260127",
        "Kimi K2.5",
        256000,
        false,
        false,
        true,
        false,
    ),
    (
        "seed-1-8-251228",
        "Seed 1.8",
        256000,
        false,
        false,
        true,
        false,
    ),
];

/// cerebras: 3 models (2 unverified).
pub static CEREBRAS_MODELS: &[CatalogRow] = &[
    (
        "gpt-oss-120b",
        "GPT OSS 120B",
        131072,
        true,
        true,
        true,
        true,
    ),
    (
        "llama3.1-8b",
        "Llama 3.1 8B",
        128000,
        false,
        false,
        true,
        false,
    ),
    ("zai-glm-4.7", "GLM 4.7", 128000, true, false, true, false),
];

/// chutes: 15 models (0 unverified).
pub static CHUTES_MODELS: &[CatalogRow] = &[
    (
        "MiniMaxAI/MiniMax-M2.5-TEE",
        "MiniMax-M2.5-TEE",
        196608,
        true,
        false,
        true,
        true,
    ),
    (
        "Nemotron-3-Nano-Omni-30B-TEE",
        "Nemotron-3-Nano-Omni-30B-TEE",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "Qwen/Qwen3-235B-A22B-Thinking-2507-TEE",
        "Qwen3-235B-A22B-Thinking-2507-TEE",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-32B-TEE",
        "Qwen3-32B-TEE",
        40960,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-397B-A17B-TEE",
        "Qwen3.5-397B-A17B-TEE",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.6-27B-TEE",
        "Qwen3.6-27B-TEE",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3.2-TEE",
        "DeepSeek-V3.2-TEE",
        131072,
        true,
        false,
        true,
        true,
    ),
    (
        "google/gemma-4-31B-turbo-TEE",
        "gemma-4-31B-turbo-TEE",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2.5-TEE",
        "Kimi-K2.5-TEE",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2.6-TEE",
        "Kimi-K2.6-TEE",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K3-TEE",
        "Kimi-K3-TEE",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "unsloth/Mistral-Nemo-Instruct-2407-TEE",
        "Mistral-Nemo-Instruct-2407-TEE",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "zai-org/GLM-5-TEE",
        "GLM-5-TEE",
        202752,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-5.1-TEE",
        "GLM-5.1-TEE",
        202752,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-5.2-TEE",
        "GLM-5.2-TEE",
        1048576,
        true,
        true,
        true,
        true,
    ),
];

/// deepinfra: 104 models (0 unverified).
pub static DEEPINFRA_MODELS: &[CatalogRow] = &[
    (
        "ByteDance/Seed-1.8",
        "Seed-1.8",
        256000,
        false,
        false,
        true,
        true,
    ),
    (
        "ByteDance/Seed-2.0-code",
        "Seed-2.0-code",
        256000,
        false,
        false,
        true,
        true,
    ),
    (
        "ByteDance/Seed-2.0-mini",
        "Seed-2.0-mini",
        256000,
        true,
        true,
        true,
        true,
    ),
    (
        "ByteDance/Seed-2.0-pro",
        "Seed-2.0-pro",
        256000,
        false,
        false,
        true,
        true,
    ),
    (
        "Gryphe/MythoMax-L2-13b",
        "MythoMax-L2-13b",
        4096,
        false,
        false,
        false,
        true,
    ),
    (
        "MiniMaxAI/MiniMax-M2.7",
        "MiniMax-M2.7",
        196608,
        true,
        false,
        true,
        true,
    ),
    (
        "MiniMaxAI/MiniMax-M2.7-Turbo",
        "MiniMax-M2.7-Turbo",
        196608,
        true,
        false,
        true,
        true,
    ),
    (
        "MiniMaxAI/MiniMax-M3",
        "MiniMax-M3",
        524288,
        true,
        false,
        true,
        true,
    ),
    (
        "NousResearch/Hermes-3-Llama-3.1-405B",
        "Hermes-3-Llama-3.1-405B",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "NousResearch/Hermes-3-Llama-3.1-70B",
        "Hermes-3-Llama-3.1-70B",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "Qwen/Qwen2.5-72B-Instruct",
        "Qwen2.5-72B-Instruct",
        32768,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-14B",
        "Qwen3-14B",
        40960,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-235B-A22B-Instruct-2507",
        "Qwen3-235B-A22B-Instruct-2507",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-235B-A22B-Thinking-2507",
        "Qwen3-235B-A22B-Thinking-2507",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-30B-A3B",
        "Qwen3-30B-A3B",
        40960,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-32B",
        "Qwen3-32B",
        40960,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo",
        "Qwen3-Coder-480B-A35B-Instruct-Turbo",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-Max",
        "Qwen3-Max",
        256000,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-Max-Thinking",
        "Qwen3-Max-Thinking",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-Next-80B-A3B-Instruct",
        "Qwen3-Next-80B-A3B-Instruct",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-VL-235B-A22B-Instruct",
        "Qwen3-VL-235B-A22B-Instruct",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-VL-30B-A3B-Instruct",
        "Qwen3-VL-30B-A3B-Instruct",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-122B-A10B",
        "Qwen3.5-122B-A10B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-27B",
        "Qwen3.5-27B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-35B-A3B",
        "Qwen3.5-35B-A3B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-397B-A17B",
        "Qwen3.5-397B-A17B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-9B",
        "Qwen3.5-9B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.6-27B",
        "Qwen3.6-27B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.6-35B-A3B",
        "Qwen3.6-35B-A3B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.7-Max",
        "Qwen3.7-Max",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "Sao10K/L3-8B-Lunaris-v1-Turbo",
        "L3-8B-Lunaris-v1-Turbo",
        8192,
        false,
        false,
        true,
        true,
    ),
    (
        "Sao10K/L3.1-70B-Euryale-v2.2",
        "L3.1-70B-Euryale-v2.2",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "XiaomiMiMo/MiMo-V2.5",
        "MiMo-V2.5",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "XiaomiMiMo/MiMo-V2.5-Pro",
        "MiMo-V2.5-Pro",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "anthropic/claude-fable-5",
        "claude-fable-5",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "anthropic/claude-haiku-4-5",
        "claude-haiku-4-5",
        200000,
        false,
        false,
        true,
        true,
    ),
    (
        "anthropic/claude-opus-4-7",
        "claude-opus-4-7",
        1000000,
        false,
        false,
        true,
        true,
    ),
    (
        "anthropic/claude-opus-4-8",
        "claude-opus-4-8",
        1000000,
        false,
        false,
        true,
        true,
    ),
    (
        "anthropic/claude-opus-5",
        "claude-opus-5",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "anthropic/claude-sonnet-4-6",
        "claude-sonnet-4-6",
        1000000,
        false,
        false,
        true,
        true,
    ),
    (
        "anthropic/claude-sonnet-5",
        "claude-sonnet-5",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-R1-0528",
        "DeepSeek-R1-0528",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3",
        "DeepSeek-V3",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3-0324",
        "DeepSeek-V3-0324",
        163840,
        false,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3.1",
        "DeepSeek-V3.1",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3.1-Terminus",
        "DeepSeek-V3.1-Terminus",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3.2",
        "DeepSeek-V3.2",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V4-Flash",
        "DeepSeek-V4-Flash",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V4-Pro",
        "DeepSeek-V4-Pro",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "google/gemini-1.5-flash",
        "gemini-1.5-flash",
        1000000,
        false,
        false,
        true,
        true,
    ),
    (
        "google/gemini-1.5-flash-8b",
        "gemini-1.5-flash-8b",
        1000000,
        false,
        false,
        true,
        true,
    ),
    (
        "google/gemini-2.5-flash",
        "gemini-2.5-flash",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "google/gemini-2.5-pro",
        "gemini-2.5-pro",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "google/gemini-3.1-flash-lite",
        "gemini-3.1-flash-lite",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "google/gemini-3.1-pro",
        "gemini-3.1-pro",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "google/gemini-3.5-flash",
        "gemini-3.5-flash",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "google/gemma-3-12b-it",
        "gemma-3-12b-it",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "google/gemma-3-27b-it",
        "gemma-3-27b-it",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "google/gemma-3-4b-it",
        "gemma-3-4b-it",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "google/gemma-4-26B-A4B-it",
        "gemma-4-26B-A4B-it",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "google/gemma-4-31B-it",
        "gemma-4-31B-it",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "google/gemma-4-31B-it-Ultra",
        "gemma-4-31B-it-Ultra",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "google/gemma-4-31B-it-turbo",
        "gemma-4-31B-it-turbo",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "google/gemma-4-E4B-it",
        "gemma-4-E4B-it",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "intfloat/e5-base-v2",
        "e5-base-v2",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "intfloat/e5-large-v2",
        "e5-large-v2",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "intfloat/multilingual-e5-large",
        "multilingual-e5-large",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "intfloat/multilingual-e5-large-instruct",
        "multilingual-e5-large-instruct",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        "Llama-3.3-70B-Instruct-Turbo",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        "Llama-4-Maverick-17B-128E-Instruct-FP8",
        1048576,
        false,
        false,
        true,
        true,
    ),
    (
        "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        "Llama-4-Scout-17B-16E-Instruct",
        327680,
        false,
        false,
        true,
        true,
    ),
    (
        "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
        "Meta-Llama-3.1-70B-Instruct-Turbo",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
        "Meta-Llama-3.1-8B-Instruct-Turbo",
        131072,
        false,
        false,
        true,
        true,
    ),
    ("microsoft/phi-4", "phi-4", 16384, false, false, false, true),
    (
        "mistralai/Mistral-Nemo-Instruct-2407",
        "Mistral-Nemo-Instruct-2407",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "mistralai/Mistral-Small-24B-Instruct-2501",
        "Mistral-Small-24B-Instruct-2501",
        32768,
        false,
        false,
        false,
        true,
    ),
    (
        "mistralai/Mistral-Small-3.2-24B-Instruct-2506",
        "Mistral-Small-3.2-24B-Instruct-2506",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2.5",
        "Kimi-K2.5",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2.6",
        "Kimi-K2.6",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2.7-Code",
        "Kimi-K2.7-Code",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B",
        "NVIDIA-Nemotron-3-Super-120B-A12B",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B",
        "NVIDIA-Nemotron-3-Ultra-550B-A55B",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "nvidia/Nemotron-3-Nano-30B-A3B",
        "Nemotron-3-Nano-30B-A3B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "openai/gpt-oss-120b",
        "gpt-oss-120b",
        131072,
        true,
        true,
        true,
        true,
    ),
    (
        "openai/gpt-oss-120b-Turbo",
        "gpt-oss-120b-Turbo",
        131072,
        true,
        true,
        true,
        true,
    ),
    (
        "openai/gpt-oss-120b-Ultra",
        "gpt-oss-120b-Ultra",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "openai/gpt-oss-20b",
        "gpt-oss-20b",
        131072,
        true,
        true,
        true,
        true,
    ),
    (
        "sentence-transformers/all-MiniLM-L12-v2",
        "all-MiniLM-L12-v2",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "sentence-transformers/all-MiniLM-L6-v2",
        "all-MiniLM-L6-v2",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "sentence-transformers/all-mpnet-base-v2",
        "all-mpnet-base-v2",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "sentence-transformers/multi-qa-mpnet-base-dot-v1",
        "multi-qa-mpnet-base-dot-v1",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "sentence-transformers/paraphrase-MiniLM-L6-v2",
        "paraphrase-MiniLM-L6-v2",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "shibing624/text2vec-base-chinese",
        "text2vec-base-chinese",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "stepfun-ai/Step-3.7-Flash",
        "Step-3.7-Flash",
        262144,
        true,
        true,
        true,
        true,
    ),
    ("tencent/Hy3", "Hy3", 262144, true, true, true, true),
    (
        "thenlper/gte-base",
        "gte-base",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "thenlper/gte-large",
        "gte-large",
        512,
        false,
        false,
        true,
        true,
    ),
    (
        "thinkingmachines/Inkling",
        "Inkling",
        524288,
        true,
        true,
        true,
        true,
    ),
    (
        "zai-org/GLM-4.6",
        "GLM-4.6",
        202752,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-4.7",
        "GLM-4.7",
        202752,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-4.7-Flash",
        "GLM-4.7-Flash",
        202752,
        true,
        false,
        true,
        true,
    ),
    ("zai-org/GLM-5", "GLM-5", 202752, true, false, true, true),
    (
        "zai-org/GLM-5.1",
        "GLM-5.1",
        202752,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-5.2",
        "GLM-5.2",
        1048576,
        true,
        true,
        true,
        true,
    ),
];

/// deepseek: 4 models (1 unverified).
pub static DEEPSEEK_MODELS: &[CatalogRow] = &[
    (
        "deepseek-chat",
        "DeepSeek Chat (V3)",
        163840,
        false,
        false,
        true,
        true,
    ),
    (
        "deepseek-reasoner",
        "DeepSeek Reasoner (R1)",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "deepseek-v4-flash",
        "DeepSeek V4 Flash",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "deepseek-v4-pro",
        "DeepSeek V4 Pro",
        1048576,
        true,
        true,
        true,
        true,
    ),
];

/// github-copilot: 13 models (0 unverified).
pub static GITHUB_COPILOT_MODELS: &[CatalogRow] = &[
    (
        "claude-opus-4.6",
        "Claude Opus 4.6",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-sonnet-4.5",
        "Claude Sonnet 4.5",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-sonnet-4.6",
        "Claude Sonnet 4.6",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-2.5-pro",
        "Gemini 2.5 Pro",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "gemini-3.1-pro",
        "Gemini 3.1 Pro",
        1048576,
        true,
        true,
        true,
        true,
    ),
    ("gpt-5-mini", "GPT-5 Mini", 400000, true, true, true, true),
    (
        "gpt-5.2-codex",
        "GPT-5.2 Codex",
        400000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.3-codex",
        "GPT-5.3 Codex",
        400000,
        true,
        true,
        true,
        true,
    ),
    ("gpt-5.4", "GPT-5.4", 1050000, true, true, true, true),
    ("gpt-5.5", "GPT-5.5", 1050000, true, true, true, true),
    (
        "gpt-5.6-luna",
        "GPT-5.6 Luna",
        1050000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.6-sol",
        "GPT-5.6 Sol",
        1050000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.6-terra",
        "GPT-5.6 Terra",
        1050000,
        true,
        true,
        true,
        true,
    ),
];

/// google: 27 models (0 unverified).
pub static GOOGLE_MODELS: &[CatalogRow] = &[
    (
        "gemini-2.5-flash",
        "Gemini 2.5 Flash",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "gemini-2.5-flash-image",
        "Nano Banana (Gemini 2.5 Flash Image)",
        32768,
        false,
        false,
        false,
        true,
    ),
    (
        "gemini-2.5-flash-lite",
        "Gemini 2.5 Flash Lite",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "gemini-2.5-pro",
        "Gemini 2.5 Pro",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "gemini-2.5-pro-preview",
        "Gemini 2.5 Pro Preview 06-05",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "gemini-2.5-pro-preview-05-06",
        "Gemini 2.5 Pro Preview 05-06",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "gemini-3-flash-preview",
        "Gemini 3 Flash Preview",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-3-pro-image",
        "Nano Banana Pro (Gemini 3 Pro Image)",
        131072,
        true,
        false,
        true,
        true,
    ),
    (
        "gemini-3-pro-image-preview",
        "Nano Banana Pro (Gemini 3 Pro Image Preview)",
        65536,
        true,
        false,
        false,
        true,
    ),
    (
        "gemini-3.1-flash-image",
        "Nano Banana 2 (Gemini 3.1 Flash Image)",
        131072,
        true,
        true,
        false,
        true,
    ),
    (
        "gemini-3.1-flash-image-preview",
        "Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
        65536,
        true,
        true,
        false,
        true,
    ),
    (
        "gemini-3.1-flash-lite",
        "Gemini 3.1 Flash Lite",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-3.1-flash-lite-image",
        "Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
        65536,
        true,
        true,
        false,
        true,
    ),
    (
        "gemini-3.1-flash-lite-preview",
        "Gemini 3.1 Flash Lite Preview",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-3.1-pro-preview",
        "Gemini 3.1 Pro Preview",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-3.1-pro-preview-customtools",
        "Gemini 3.1 Pro Preview Custom Tools",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-3.5-flash",
        "Gemini 3.5 Flash",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-3.5-flash-lite",
        "Gemini 3.5 Flash Lite",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-3.6-flash",
        "Gemini 3.6 Flash",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gemma-2-27b-it",
        "Gemma 2 27B",
        8192,
        false,
        false,
        false,
        true,
    ),
    (
        "gemma-3-12b-it",
        "Gemma 3 12B",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "gemma-3-27b-it",
        "Gemma 3 27B",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "gemma-3-4b-it",
        "Gemma 3 4B",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "gemma-3n-e4b-it",
        "Gemma 3n 4B",
        32768,
        false,
        false,
        false,
        true,
    ),
    (
        "gemma-4-26b-a4b-it",
        "Gemma 4 26B A4B ",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "gemma-4-31b-it",
        "Gemma 4 31B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "lyria-3-pro-preview",
        "Lyria 3 Pro Preview",
        1048576,
        false,
        false,
        false,
        true,
    ),
];

/// google-gemini-cli: 2 models (0 unverified).
pub static GOOGLE_GEMINI_CLI_MODELS: &[CatalogRow] = &[
    (
        "google/gemini-2.5-flash",
        "Gemini 2.5 Flash",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "google/gemini-2.5-pro",
        "Gemini 2.5 Pro",
        1048576,
        true,
        false,
        true,
        true,
    ),
];

/// grok-cli: 2 models (1 unverified).
pub static GROK_CLI_MODELS: &[CatalogRow] = &[
    ("grok-4.5", "Grok 4.5", 500000, true, true, true, true),
    (
        "grok-composer-2.5-fast",
        "Composer 2.5 (fast)",
        200000,
        false,
        false,
        true,
        false,
    ),
];

/// groq: 5 models (4 unverified).
pub static GROQ_MODELS: &[CatalogRow] = &[
    (
        "llama-3.1-8b-instant",
        "Llama 3.1 8B",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "llama-3.3-70b-versatile",
        "Llama 3.3 70B",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistral-saba-24b",
        "Mistral Saba 24B",
        32768,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen-qwq-32b",
        "Qwen QwQ 32B",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-32b",
        "Qwen3 32B",
        131072,
        true,
        false,
        true,
        true,
    ),
];

/// huggingface: 97 models (0 unverified).
pub static HUGGINGFACE_MODELS: &[CatalogRow] = &[
    (
        "MiniMaxAI/MiniMax-M1-80k",
        "MiniMax-M1-80k",
        1000000,
        false,
        false,
        true,
        true,
    ),
    (
        "MiniMaxAI/MiniMax-M2",
        "MiniMax-M2",
        204800,
        true,
        false,
        true,
        true,
    ),
    (
        "MiniMaxAI/MiniMax-M2.1",
        "MiniMax-M2.1",
        204800,
        true,
        false,
        true,
        true,
    ),
    (
        "MiniMaxAI/MiniMax-M2.5",
        "MiniMax-M2.5",
        204800,
        true,
        false,
        true,
        true,
    ),
    (
        "MiniMaxAI/MiniMax-M2.7",
        "MiniMax-M2.7",
        204800,
        true,
        false,
        true,
        true,
    ),
    (
        "MiniMaxAI/MiniMax-M3",
        "MiniMax-M3",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen2.5-72B-Instruct",
        "Qwen2.5-72B-Instruct",
        32768,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen2.5-7B-Instruct",
        "Qwen2.5-7B-Instruct",
        32768,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen2.5-Coder-32B-Instruct",
        "Qwen2.5-Coder-32B-Instruct",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "Qwen/Qwen2.5-Coder-3B-Instruct",
        "Qwen2.5-Coder-3B-Instruct",
        32768,
        false,
        false,
        false,
        true,
    ),
    (
        "Qwen/Qwen2.5-Coder-7B-Instruct",
        "Qwen2.5-Coder-7B-Instruct",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "Qwen/Qwen2.5-VL-72B-Instruct",
        "Qwen2.5-VL-72B-Instruct",
        32768,
        false,
        false,
        false,
        true,
    ),
    (
        "Qwen/Qwen3-14B",
        "Qwen3-14B",
        40960,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-235B-A22B",
        "Qwen3-235B-A22B",
        40960,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-235B-A22B-Instruct-2507",
        "Qwen3-235B-A22B-Instruct-2507",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-235B-A22B-Thinking-2507",
        "Qwen3-235B-A22B-Thinking-2507",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-32B",
        "Qwen3-32B",
        40960,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-4B-Instruct-2507",
        "Qwen3-4B-Instruct-2507",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-4B-Thinking-2507",
        "Qwen3-4B-Thinking-2507",
        262144,
        false,
        false,
        true,
        true,
    ),
    ("Qwen/Qwen3-8B", "Qwen3-8B", 40960, true, false, true, true),
    (
        "Qwen/Qwen3-Coder-480B-A35B-Instruct",
        "Qwen3-Coder-480B-A35B-Instruct",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-Coder-Next",
        "Qwen3-Coder-Next",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-Next-80B-A3B-Instruct",
        "Qwen3-Next-80B-A3B-Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-VL-235B-A22B-Instruct",
        "Qwen3-VL-235B-A22B-Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-VL-235B-A22B-Thinking",
        "Qwen3-VL-235B-A22B-Thinking",
        131072,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3-VL-30B-A3B-Instruct",
        "Qwen3-VL-30B-A3B-Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-122B-A10B",
        "Qwen3.5-122B-A10B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-27B",
        "Qwen3.5-27B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-35B-A3B",
        "Qwen3.5-35B-A3B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-397B-A17B",
        "Qwen3.5-397B-A17B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.5-9B",
        "Qwen3.5-9B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.6-27B",
        "Qwen3.6-27B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Qwen/Qwen3.6-35B-A3B",
        "Qwen3.6-35B-A3B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "Sao10K/L3-8B-Lunaris-v1",
        "L3-8B-Lunaris-v1",
        8192,
        false,
        false,
        false,
        true,
    ),
    (
        "Sao10K/L3-8B-Stheno-v3.2",
        "L3-8B-Stheno-v3.2",
        8192,
        false,
        false,
        false,
        true,
    ),
    (
        "XiaomiMiMo/MiMo-V2.5",
        "MiMo-V2.5",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "XiaomiMiMo/MiMo-V2.5-Pro",
        "MiMo-V2.5-Pro",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "alpindale/WizardLM-2-8x22B",
        "WizardLM-2-8x22B",
        65535,
        false,
        false,
        false,
        true,
    ),
    (
        "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT",
        "ERNIE-4.5-VL-424B-A47B-Base-PT",
        123000,
        false,
        false,
        false,
        true,
    ),
    (
        "deepcogito/cogito-671b-v2.1",
        "cogito-671b-v2.1",
        163840,
        false,
        false,
        false,
        true,
    ),
    (
        "deepcogito/cogito-671b-v2.1-FP8",
        "cogito-671b-v2.1-FP8",
        163840,
        false,
        false,
        false,
        true,
    ),
    (
        "deepreinforce-ai/Ornith-1.0-35B",
        "Ornith-1.0-35B",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "deepreinforce-ai/Ornith-1.0-35B-FP8",
        "Ornith-1.0-35B-FP8",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-R1",
        "DeepSeek-R1",
        64000,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-R1-0528",
        "DeepSeek-R1-0528",
        163840,
        true,
        false,
        false,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
        "DeepSeek-R1-Distill-Llama-70B",
        8192,
        true,
        false,
        false,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
        "DeepSeek-R1-Distill-Llama-8B",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
        "DeepSeek-R1-Distill-Qwen-14B",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
        "DeepSeek-R1-Distill-Qwen-7B",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3",
        "DeepSeek-V3",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3-0324",
        "DeepSeek-V3-0324",
        163840,
        false,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3.1",
        "DeepSeek-V3.1",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3.1-Terminus",
        "DeepSeek-V3.1-Terminus",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3.2",
        "DeepSeek-V3.2",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3.2-Exp",
        "DeepSeek-V3.2-Exp",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V4-Flash",
        "DeepSeek-V4-Flash",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V4-Pro",
        "DeepSeek-V4-Pro",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "google/gemma-3-12b-it",
        "gemma-3-12b-it",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "google/gemma-3-27b-it",
        "gemma-3-27b-it",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "google/gemma-3-4b-it",
        "gemma-3-4b-it",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "google/gemma-3n-E4B-it",
        "gemma-3n-E4B-it",
        32768,
        false,
        false,
        false,
        true,
    ),
    (
        "google/gemma-4-26B-A4B-it",
        "gemma-4-26B-A4B-it",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "google/gemma-4-31B-it",
        "gemma-4-31B-it",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "inclusionAI/Ling-2.6-1T",
        "Ling-2.6-1T",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "meta-llama/Llama-3.1-8B-Instruct",
        "Llama-3.1-8B-Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "meta-llama/Llama-3.3-70B-Instruct",
        "Llama-3.3-70B-Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",
        "Llama-4-Maverick-17B-128E-Instruct-FP8",
        1048576,
        false,
        false,
        false,
        true,
    ),
    (
        "meta-llama/Llama-4-Scout-17B-16E-Instruct",
        "Llama-4-Scout-17B-16E-Instruct",
        890000,
        false,
        false,
        true,
        true,
    ),
    ("microsoft/phi-4", "phi-4", 16384, false, false, false, true),
    (
        "moonshotai/Kimi-K2-Instruct",
        "Kimi-K2-Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2-Instruct-0905",
        "Kimi-K2-Instruct-0905",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2.5",
        "Kimi-K2.5",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2.6",
        "Kimi-K2.6",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2.7-Code",
        "Kimi-K2.7-Code",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K3",
        "Kimi-K3",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
        "NVIDIA-Nemotron-3-Ultra-550B-A55B-BF16",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4",
        "NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4",
        512288,
        false,
        false,
        true,
        true,
    ),
    (
        "openai/gpt-oss-120b",
        "gpt-oss-120b",
        131072,
        true,
        true,
        true,
        true,
    ),
    (
        "openai/gpt-oss-20b",
        "gpt-oss-20b",
        131072,
        true,
        true,
        true,
        true,
    ),
    (
        "pearl-ai/Gemma-4-31B-it-pearl",
        "Gemma-4-31B-it-pearl",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "prism-ml/Ternary-Bonsai-27B-AWQ-4bit",
        "Ternary-Bonsai-27B-AWQ-4bit",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "prism-ml/Ternary-Bonsai-27B-gguf",
        "Ternary-Bonsai-27B-gguf",
        262144,
        false,
        false,
        true,
        true,
    ),
    (
        "stepfun-ai/Step-3.5-Flash",
        "Step-3.5-Flash",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "stepfun-ai/Step-3.7-Flash",
        "Step-3.7-Flash",
        262144,
        true,
        true,
        true,
        true,
    ),
    ("tencent/Hy3", "Hy3", 262144, true, true, true, true),
    (
        "thinkingmachines/Inkling",
        "Inkling",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "zai-org/AutoGLM-Phone-9B-Multilingual",
        "AutoGLM-Phone-9B-Multilingual",
        65536,
        false,
        false,
        false,
        true,
    ),
    (
        "zai-org/GLM-4-32B-0414",
        "GLM-4-32B-0414",
        32000,
        false,
        false,
        false,
        true,
    ),
    (
        "zai-org/GLM-4.5-Air",
        "GLM-4.5-Air",
        131072,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-4.5V",
        "GLM-4.5V",
        65536,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-4.6",
        "GLM-4.6",
        204800,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-4.6V-Flash",
        "GLM-4.6V-Flash",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-4.7",
        "GLM-4.7",
        204800,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-4.7-Flash",
        "GLM-4.7-Flash",
        202752,
        true,
        false,
        true,
        true,
    ),
    ("zai-org/GLM-5", "GLM-5", 202800, true, false, true, true),
    (
        "zai-org/GLM-5.1",
        "GLM-5.1",
        202752,
        true,
        false,
        true,
        true,
    ),
    (
        "zai-org/GLM-5.2",
        "GLM-5.2",
        1048576,
        true,
        true,
        true,
        true,
    ),
];

/// kilocode: 1 models (0 unverified).
pub static KILOCODE_MODELS: &[CatalogRow] = &[(
    "kilo/auto",
    "Kilo Auto (multi-modal)",
    2000000,
    true,
    true,
    true,
    true,
)];

/// kimi-coding: 2 models (2 unverified).
pub static KIMI_CODING_MODELS: &[CatalogRow] = &[
    (
        "kimi-for-coding",
        "Kimi for Coding (K3-class)",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "kimi-for-coding-highspeed",
        "Kimi for Coding HighSpeed",
        262144,
        true,
        false,
        true,
        false,
    ),
];

/// meta: 7 models (0 unverified).
pub static META_MODELS: &[CatalogRow] = &[
    (
        "llama-3.1-70b-instruct",
        "Llama 3.1 70B Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "llama-3.1-8b-instruct",
        "Llama 3.1 8B Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "llama-3.2-1b-instruct",
        "Llama 3.2 1B Instruct",
        60000,
        false,
        false,
        false,
        true,
    ),
    (
        "llama-3.2-3b-instruct",
        "Llama 3.2 3B Instruct",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "llama-3.3-70b-instruct",
        "Llama 3.3 70B Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "llama-4-maverick",
        "Llama 4 Maverick",
        1048576,
        false,
        false,
        true,
        true,
    ),
    (
        "llama-4-scout",
        "Llama 4 Scout",
        1310720,
        false,
        false,
        true,
        true,
    ),
];

/// minimax-portal: 3 models (0 unverified).
pub static MINIMAX_PORTAL_MODELS: &[CatalogRow] = &[
    (
        "MiniMax-M2.5",
        "MiniMax M2.5",
        204800,
        true,
        false,
        true,
        true,
    ),
    (
        "MiniMax-M2.7",
        "MiniMax M2.7",
        204800,
        true,
        false,
        true,
        true,
    ),
    ("MiniMax-M3", "MiniMax M3", 1048576, true, false, true, true),
];

/// mistral: 6 models (4 unverified).
pub static MISTRAL_MODELS: &[CatalogRow] = &[
    (
        "codestral-latest",
        "Codestral",
        256000,
        false,
        false,
        true,
        false,
    ),
    (
        "magistral-small",
        "Magistral Small",
        128000,
        true,
        false,
        true,
        false,
    ),
    (
        "mistral-large-latest",
        "Mistral Large",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "mistral-medium-3-5",
        "Mistral Medium 3.5",
        262144,
        true,
        true,
        true,
        true,
    ),
    (
        "mistral-small-latest",
        "Mistral Small",
        128000,
        true,
        false,
        true,
        false,
    ),
    (
        "pixtral-large-latest",
        "Pixtral Large",
        128000,
        false,
        false,
        true,
        false,
    ),
];

/// moonshot: 5 models (0 unverified).
pub static MOONSHOT_MODELS: &[CatalogRow] = &[
    (
        "kimi-k2-thinking",
        "Kimi K2 Thinking",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "kimi-k2-turbo",
        "Kimi K2 Turbo (free)",
        131072,
        false,
        false,
        true,
        true,
    ),
    ("kimi-k2.5", "Kimi K2.5", 262144, true, false, true, true),
    ("kimi-k2.6", "Kimi K2.6", 262144, true, false, true, true),
    ("kimi-k3", "Kimi K3", 1048576, true, true, true, true),
];

/// nvidia: 76 models (52 unverified).
pub static NVIDIA_MODELS: &[CatalogRow] = &[
    (
        "01-ai/yi-large",
        "yi-large",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "adept/fuyu-8b",
        "fuyu-8b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "ai21labs/jamba-1.5-large-instruct",
        "jamba-1.5-large-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "aisingapore/sea-lion-7b-instruct",
        "sea-lion-7b-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "bigcode/starcoder2-15b",
        "starcoder2-15b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "databricks/dbrx-instruct",
        "dbrx-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "deepseek-ai/deepseek-coder-6.7b-instruct",
        "deepseek-coder-6.7b-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "deepseek-ai/deepseek-v4-flash",
        "DeepSeek V4 Flash",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "deepseek-ai/deepseek-v4-pro",
        "DeepSeek V4 Pro",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "google/codegemma-1.1-7b",
        "codegemma-1.1-7b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "google/codegemma-7b",
        "codegemma-7b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "google/gemma-2b",
        "gemma-2b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "google/gemma-3-12b-it",
        "Gemma 3 12B",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "google/gemma-3-4b-it",
        "Gemma 3 4B",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "google/gemma-4-31b-it",
        "Gemma 4 31B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "google/recurrentgemma-2b",
        "recurrentgemma-2b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "ibm/granite-3.0-3b-a800m-instruct",
        "granite-3.0-3b-a800m-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "ibm/granite-3.0-8b-instruct",
        "granite-3.0-8b-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "ibm/granite-34b-code-instruct",
        "granite-34b-code-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "ibm/granite-8b-code-instruct",
        "granite-8b-code-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "meta/codellama-70b",
        "codellama-70b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "meta/llama-3.1-70b-instruct",
        "Llama 3.1 70B Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "meta/llama-3.1-8b-instruct",
        "Llama 3.1 8B Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "meta/llama-3.2-11b-vision-instruct",
        "llama-3.2-11b-vision-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "meta/llama-3.2-1b-instruct",
        "Llama 3.2 1B Instruct",
        60000,
        false,
        false,
        false,
        true,
    ),
    (
        "meta/llama-3.2-3b-instruct",
        "Llama 3.2 3B Instruct",
        131072,
        false,
        false,
        false,
        true,
    ),
    (
        "meta/llama-3.2-90b-vision-instruct",
        "llama-3.2-90b-vision-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "meta/llama-3.3-70b-instruct",
        "Llama 3.3 70B Instruct",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "meta/llama2-70b",
        "llama2-70b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "microsoft/phi-3-vision-128k-instruct",
        "phi-3-vision-128k-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "microsoft/phi-3.5-moe-instruct",
        "phi-3.5-moe-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "minimaxai/minimax-m3",
        "MiniMax M3",
        1048576,
        true,
        false,
        true,
        true,
    ),
    (
        "mistralai/codestral-22b-instruct-v0.1",
        "codestral-22b-instruct-v0.1",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-7b-instruct-v0.3",
        "mistral-7b-instruct-v0.3",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-large",
        "Mistral Large",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "mistralai/mistral-large-2-instruct",
        "mistral-large-2-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-medium-3.5-128b",
        "mistral-medium-3.5-128b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-nemotron",
        "mistral-nemotron",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mixtral-8x22b-v0.1",
        "mixtral-8x22b-v0.1",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "moonshotai/kimi-k2.6",
        "Kimi K2.6",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "nv-mistralai/mistral-nemo-12b-instruct",
        "mistral-nemo-12b-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/cosmos-reason2-8b",
        "cosmos-reason2-8b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/llama-3.1-nemotron-51b-instruct",
        "llama-3.1-nemotron-51b-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/llama-3.1-nemotron-70b-instruct",
        "llama-3.1-nemotron-70b-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/llama-3.1-nemotron-nano-8b-v1",
        "llama-3.1-nemotron-nano-8b-v1",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
        "llama-3.1-nemotron-nano-vl-8b-v1",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/llama-3.1-nemotron-ultra-253b-v1",
        "llama-3.1-nemotron-ultra-253b-v1",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/llama-3.3-nemotron-super-49b-v1",
        "llama-3.3-nemotron-super-49b-v1",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/llama-3.3-nemotron-super-49b-v1.5",
        "llama-3.3-nemotron-super-49b-v1.5",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/llama3-chatqa-1.5-70b",
        "llama3-chatqa-1.5-70b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/mistral-nemo-minitron-8b-8k-instruct",
        "mistral-nemo-minitron-8b-8k-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/nemoretriever-parse",
        "nemoretriever-parse",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/nemotron-3-nano-30b-a3b",
        "Nemotron 3 Nano 30B A3B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
        "Nemotron 3 Nano Omni (free)",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "nvidia/nemotron-3-super-120b-a12b",
        "Nemotron 3 Super",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "nvidia/nemotron-3-ultra-550b-a55b",
        "Nemotron 3 Ultra",
        512288,
        true,
        true,
        true,
        true,
    ),
    (
        "nvidia/nemotron-4-340b-instruct",
        "nemotron-4-340b-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/nemotron-4-340b-reward",
        "nemotron-4-340b-reward",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/nemotron-mini-4b-instruct",
        "nemotron-mini-4b-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/nemotron-nano-12b-v2-vl",
        "Nemotron Nano 12B 2 VL (free)",
        128000,
        true,
        false,
        true,
        true,
    ),
    (
        "nvidia/nemotron-nano-3-30b-a3b",
        "nemotron-nano-3-30b-a3b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/nemotron-parse",
        "nemotron-parse",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/neva-22b",
        "neva-22b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nvidia/nvidia-nemotron-nano-9b-v2",
        "nvidia-nemotron-nano-9b-v2",
        131072,
        false,
        false,
        true,
        false,
    ),
    ("nvidia/vila", "vila", 131072, false, false, true, false),
    (
        "openai/gpt-oss-120b",
        "gpt-oss-120b",
        131072,
        true,
        true,
        true,
        true,
    ),
    (
        "openai/gpt-oss-20b",
        "gpt-oss-20b",
        131072,
        true,
        true,
        true,
        true,
    ),
    (
        "poolside/laguna-xs-2.1",
        "Laguna XS 2.1",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "stepfun-ai/step-3.7-flash",
        "Step 3.7 Flash",
        262144,
        true,
        true,
        true,
        true,
    ),
    (
        "thinkingmachines/inkling",
        "Inkling",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "writer/palmyra-creative-122b",
        "palmyra-creative-122b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "writer/palmyra-fin-70b-32k",
        "palmyra-fin-70b-32k",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "writer/palmyra-med-70b",
        "palmyra-med-70b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "writer/palmyra-med-70b-32k",
        "palmyra-med-70b-32k",
        131072,
        false,
        false,
        true,
        false,
    ),
    ("z-ai/glm-5.2", "GLM 5.2", 1048576, true, true, true, true),
    (
        "zyphra/zamba2-7b-instruct",
        "zamba2-7b-instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
];

/// ollama: 6 models (1 unverified).
pub static OLLAMA_MODELS: &[CatalogRow] = &[
    (
        "deepseek-r1:14b",
        "DeepSeek R1 14B",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "llama3.1:70b",
        "Llama 3.1 70B",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "llama3.1:8b",
        "Llama 3.1 8B",
        131072,
        false,
        false,
        true,
        true,
    ),
    (
        "llama3.3:70b",
        "Llama 3.3 70B",
        131072,
        false,
        false,
        true,
        true,
    ),
    ("mistral:7b", "Mistral 7B", 128000, false, false, true, true),
    (
        "qwen2.5-coder:32b",
        "Qwen 2.5 Coder 32B",
        32768,
        false,
        false,
        true,
        false,
    ),
];

/// ollama-cloud: 19 models (1 unverified).
pub static OLLAMA_CLOUD_MODELS: &[CatalogRow] = &[
    (
        "deepseek-v4-flash",
        "DeepSeek V4 Flash",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "deepseek-v4-pro",
        "DeepSeek V4 Pro",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gemma4:31b",
        "Gemma 4 26B A4B ",
        262144,
        true,
        false,
        true,
        true,
    ),
    ("glm-5.1", "GLM 5.1", 204800, true, false, true, true),
    ("glm-5.2", "GLM 5.2", 1048576, true, true, true, true),
    (
        "gpt-oss:120b",
        "gpt-oss-120b",
        131072,
        true,
        true,
        true,
        true,
    ),
    ("gpt-oss:20b", "gpt-oss-20b", 131072, true, true, true, true),
    ("kimi-k2.5", "Kimi K2.5", 262144, true, false, true, true),
    ("kimi-k2.6", "Kimi K2.6", 262144, true, false, true, true),
    (
        "kimi-k2.7-code",
        "Kimi K2.7 Code",
        262144,
        true,
        false,
        true,
        true,
    ),
    ("kimi-k3", "Kimi K3", 1048576, true, true, true, true),
    (
        "minimax-m2.5",
        "MiniMax M2.5",
        204800,
        true,
        false,
        true,
        true,
    ),
    (
        "minimax-m2.7",
        "MiniMax M2.7",
        204800,
        true,
        false,
        true,
        true,
    ),
    ("minimax-m3", "MiniMax M3", 1048576, true, false, true, true),
    (
        "mistral-large-3:675b",
        "mistral-large-3:675b",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "nemotron-3-nano:30b",
        "Nemotron 3 Nano 30B A3B",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "nemotron-3-super",
        "Nemotron 3 Super",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "nemotron-3-ultra",
        "Nemotron 3 Ultra",
        512288,
        true,
        true,
        true,
        true,
    ),
    (
        "qwen3.5:397b",
        "Qwen3.5-122B-A10B",
        262144,
        true,
        false,
        true,
        true,
    ),
];

/// openai: 62 models (0 unverified).
pub static OPENAI_MODELS: &[CatalogRow] = &[
    (
        "gpt-3.5-turbo",
        "GPT-3.5 Turbo",
        16385,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-3.5-turbo-0613",
        "GPT-3.5 Turbo (older v0613)",
        4095,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-3.5-turbo-16k",
        "GPT-3.5 Turbo 16k",
        16385,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-3.5-turbo-instruct",
        "GPT-3.5 Turbo Instruct",
        4095,
        false,
        false,
        false,
        true,
    ),
    ("gpt-4", "GPT-4", 8191, false, false, true, true),
    (
        "gpt-4-turbo",
        "GPT-4 Turbo",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-4-turbo-preview",
        "GPT-4 Turbo Preview",
        128000,
        false,
        false,
        true,
        true,
    ),
    ("gpt-4.1", "GPT-4.1", 1047576, false, false, true, true),
    (
        "gpt-4.1-mini",
        "GPT-4.1 Mini",
        1047576,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-4.1-nano",
        "GPT-4.1 Nano",
        1047576,
        false,
        false,
        true,
        true,
    ),
    ("gpt-4o", "GPT-4o", 128000, false, false, true, true),
    (
        "gpt-4o-2024-05-13",
        "GPT-4o (2024-05-13)",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-4o-2024-08-06",
        "GPT-4o (2024-08-06)",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-4o-2024-11-20",
        "GPT-4o (2024-11-20)",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-4o-mini",
        "GPT-4o-mini",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-4o-mini-2024-07-18",
        "GPT-4o-mini (2024-07-18)",
        128000,
        false,
        false,
        true,
        true,
    ),
    ("gpt-5", "GPT-5", 400000, true, true, true, true),
    (
        "gpt-5-codex",
        "GPT-5 Codex",
        400000,
        true,
        false,
        true,
        true,
    ),
    (
        "gpt-5-image",
        "GPT-5 Image",
        400000,
        true,
        false,
        false,
        true,
    ),
    (
        "gpt-5-image-mini",
        "GPT-5 Image Mini",
        400000,
        true,
        false,
        false,
        true,
    ),
    ("gpt-5-mini", "GPT-5 Mini", 400000, true, true, true, true),
    ("gpt-5-nano", "GPT-5 Nano", 400000, true, true, true, true),
    ("gpt-5-pro", "GPT-5 Pro", 400000, true, true, true, true),
    ("gpt-5.1", "GPT-5.1", 400000, true, true, true, true),
    (
        "gpt-5.1-chat",
        "GPT-5.1 Chat",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-5.1-codex",
        "GPT-5.1-Codex",
        400000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.1-codex-max",
        "GPT-5.1-Codex-Max",
        400000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.1-codex-mini",
        "GPT-5.1-Codex-Mini",
        400000,
        true,
        true,
        true,
        true,
    ),
    ("gpt-5.2", "GPT-5.2", 400000, true, true, true, true),
    (
        "gpt-5.2-chat",
        "GPT-5.2 Chat",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-5.2-codex",
        "GPT-5.2-Codex",
        400000,
        true,
        true,
        true,
        true,
    ),
    ("gpt-5.2-pro", "GPT-5.2 Pro", 400000, true, true, true, true),
    (
        "gpt-5.3-chat",
        "GPT-5.3 Chat",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-5.3-codex",
        "GPT-5.3-Codex",
        400000,
        true,
        true,
        true,
        true,
    ),
    ("gpt-5.4", "GPT-5.4", 1050000, true, true, true, true),
    (
        "gpt-5.4-image-2",
        "GPT-5.4 Image 2",
        272000,
        true,
        true,
        false,
        true,
    ),
    (
        "gpt-5.4-mini",
        "GPT-5.4 Mini",
        400000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.4-nano",
        "GPT-5.4 Nano",
        400000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.4-pro",
        "GPT-5.4 Pro",
        1050000,
        true,
        true,
        true,
        true,
    ),
    ("gpt-5.5", "GPT-5.5", 1050000, true, true, true, true),
    (
        "gpt-5.5-pro",
        "GPT-5.5 Pro",
        1050000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.6-luna",
        "GPT-5.6 Luna",
        1050000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.6-luna-pro",
        "GPT-5.6 Luna Pro",
        1050000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.6-sol",
        "GPT-5.6 Sol",
        1050000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.6-sol-pro",
        "GPT-5.6 Sol Pro",
        1050000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.6-terra",
        "GPT-5.6 Terra",
        1050000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.6-terra-pro",
        "GPT-5.6 Terra Pro",
        1050000,
        true,
        true,
        true,
        true,
    ),
    ("gpt-audio", "GPT Audio", 128000, false, false, true, true),
    (
        "gpt-audio-mini",
        "GPT Audio Mini",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-chat-latest",
        "GPT Chat Latest",
        400000,
        false,
        false,
        true,
        true,
    ),
    (
        "gpt-oss-120b",
        "gpt-oss-120b",
        131072,
        true,
        true,
        true,
        true,
    ),
    ("gpt-oss-20b", "gpt-oss-20b", 131072, true, true, true, true),
    ("o1", "o1", 200000, true, false, true, true),
    ("o1-pro", "o1-pro", 200000, true, false, false, true),
    ("o3", "o3", 200000, true, false, true, true),
    (
        "o3-deep-research",
        "o3 Deep Research",
        200000,
        true,
        false,
        true,
        true,
    ),
    ("o3-mini", "o3 Mini", 200000, true, false, true, true),
    (
        "o3-mini-high",
        "o3 Mini High",
        200000,
        true,
        true,
        true,
        true,
    ),
    ("o3-pro", "o3 Pro", 200000, true, false, true, true),
    ("o4-mini", "o4 Mini", 200000, true, false, true, true),
    (
        "o4-mini-deep-research",
        "o4 Mini Deep Research",
        200000,
        true,
        false,
        true,
        true,
    ),
    (
        "o4-mini-high",
        "o4 Mini High",
        200000,
        true,
        true,
        true,
        true,
    ),
];

/// opencode: 9 models (4 unverified).
pub static OPENCODE_MODELS: &[CatalogRow] = &[
    (
        "big-pickle",
        "Big Pickle",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "claude-sonnet-4-5",
        "Claude Sonnet 4.5",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "claude-sonnet-4-6",
        "Claude Sonnet 4.6",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "gemini-3.1-pro",
        "Gemini 3.1 Pro",
        1048576,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.3-codex",
        "GPT-5.3 Codex",
        400000,
        true,
        true,
        true,
        true,
    ),
    (
        "gpt-5.4-mini",
        "GPT-5.4 mini",
        400000,
        true,
        true,
        true,
        true,
    ),
    ("gpt-5.5", "GPT-5.5", 1050000, true, true, true, true),
    (
        "minimax-m2.5-free",
        "MiniMax M2.5 Free",
        196608,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen3.6-plus",
        "Qwen3.6 Plus",
        1000000,
        true,
        false,
        true,
        true,
    ),
];

/// qianfan: 1 models (0 unverified).
pub static QIANFAN_MODELS: &[CatalogRow] = &[(
    "deepseek-v3.2",
    "DeepSeek V3.2",
    163840,
    true,
    false,
    true,
    true,
)];

/// stepfun: 1 models (0 unverified).
pub static STEPFUN_MODELS: &[CatalogRow] = &[(
    "step-3.5-flash",
    "Step 3.5 Flash (free)",
    262144,
    true,
    false,
    true,
    true,
)];

/// tencent: 1 models (0 unverified).
pub static TENCENT_MODELS: &[CatalogRow] =
    &[("hy3-preview", "Hy3 Preview", 262144, true, true, true, true)];

/// together: 3 models (0 unverified).
pub static TOGETHER_MODELS: &[CatalogRow] = &[
    (
        "deepseek-ai/DeepSeek-R1",
        "DeepSeek R1",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-ai/DeepSeek-V3.1",
        "DeepSeek V3.1",
        163840,
        true,
        false,
        true,
        true,
    ),
    (
        "moonshotai/Kimi-K2.5",
        "Kimi K2.5",
        262144,
        true,
        false,
        true,
        true,
    ),
];

/// venice: 105 models (0 unverified).
pub static VENICE_MODELS: &[CatalogRow] = &[
    (
        "aion-labs-aion-3-0",
        "Aion 3.0",
        128000,
        true,
        true,
        true,
        true,
    ),
    (
        "aion-labs-aion-3-0-mini",
        "Aion 3.0 Mini",
        128000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-fable-5",
        "Claude Fable 5",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "claude-opus-4-5",
        "Claude Opus 4.5",
        198000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-4-6",
        "Claude Opus 4.6",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-4-7",
        "Claude Opus 4.7",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-4-8",
        "Claude Opus 4.8",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-4-8-fast",
        "Claude Opus 4.8 Fast",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-5",
        "Claude Opus 5",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-opus-5-fast",
        "Claude Opus 5 Fast",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-sonnet-4-5",
        "Claude Sonnet 4.5",
        198000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-sonnet-4-6",
        "Claude Sonnet 4.6",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "claude-sonnet-5",
        "Claude Sonnet 5",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-v3.2",
        "DeepSeek V3.2",
        160000,
        true,
        true,
        true,
        true,
    ),
    (
        "deepseek-v4-flash",
        "DeepSeek V4 Flash",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "deepseek-v4-pro",
        "DeepSeek V4 Pro",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "e2ee-deepseek-v4-flash",
        "DeepSeek V4 Flash",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "e2ee-gemma-3-27b-p",
        "Gemma 3 27B",
        40000,
        false,
        false,
        false,
        true,
    ),
    (
        "e2ee-gemma-4-26b-a4b-uncensored-p",
        "Gemma 4 26B A4B Uncensored",
        64000,
        false,
        false,
        false,
        true,
    ),
    (
        "e2ee-gemma-4-31b",
        "Gemma 4 31B Instruct",
        32000,
        true,
        false,
        false,
        true,
    ),
    ("e2ee-glm-4-7-p", "GLM 4.7", 128000, true, true, false, true),
    ("e2ee-glm-5-1", "GLM 5.1", 200000, true, false, false, true),
    ("e2ee-glm-5-2-p", "GLM 5.2", 524288, true, true, true, true),
    (
        "e2ee-gpt-oss-120b-p",
        "GPT OSS 120B",
        128000,
        true,
        true,
        false,
        true,
    ),
    (
        "e2ee-gpt-oss-20b-p",
        "GPT OSS 20B",
        128000,
        true,
        true,
        false,
        true,
    ),
    (
        "e2ee-qwen-2-5-7b-p",
        "Qwen 2.5 7B",
        32000,
        false,
        false,
        false,
        true,
    ),
    (
        "e2ee-qwen3-30b-a3b-p",
        "Qwen3 30B A3B",
        256000,
        false,
        false,
        true,
        true,
    ),
    (
        "e2ee-qwen3-6-27b",
        "Qwen 3.6 27B FP8",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "e2ee-qwen3-6-35b-a3b",
        "Qwen 3.6 35B A3B FP8",
        32000,
        true,
        false,
        true,
        true,
    ),
    (
        "e2ee-qwen3-6-35b-a3b-uncensored-p",
        "Qwen3.6 35B A3B Uncensored",
        128000,
        false,
        false,
        false,
        true,
    ),
    (
        "e2ee-qwen3-vl-30b-a3b-p",
        "Qwen3 VL 30B A3B",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "e2ee-venice-uncensored-24b-p",
        "Venice Uncensored 1.1",
        32000,
        false,
        false,
        false,
        true,
    ),
    (
        "gemini-3-1-pro-preview",
        "Gemini 3.1 Pro Preview",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-3-5-flash",
        "Gemini 3.5 Flash",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "gemini-3-5-flash-lite",
        "Gemini 3.5 Flash-Lite",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "gemini-3-6-flash",
        "Gemini 3.6 Flash",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "gemini-3-flash-preview",
        "Gemini 3 Flash Preview",
        256000,
        true,
        true,
        true,
        true,
    ),
    (
        "gemma-4-uncensored",
        "Gemma 4 Uncensored",
        256000,
        false,
        false,
        true,
        true,
    ),
    (
        "google-gemma-3-27b-it",
        "Google Gemma 3 27B Instruct",
        198000,
        false,
        false,
        true,
        true,
    ),
    (
        "google-gemma-4-26b-a4b-it",
        "Google Gemma 4 26B A4B Instruct",
        256000,
        true,
        true,
        true,
        true,
    ),
    (
        "google-gemma-4-31b-it",
        "Google Gemma 4 31B Instruct",
        256000,
        true,
        true,
        true,
        true,
    ),
    ("grok-4-20", "Grok 4.20", 2000000, true, false, true, true),
    (
        "grok-4-20-multi-agent",
        "Grok 4.20 Multi-Agent",
        2000000,
        true,
        false,
        false,
        true,
    ),
    ("grok-4-3", "Grok 4.3", 1000000, true, true, true, true),
    ("grok-4-5", "Grok 4.5", 500000, true, true, true, true),
    (
        "grok-build-0-1",
        "Grok Build 0.1",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "hermes-3-llama-3.1-405b",
        "Hermes 3 Llama 3.1 405b",
        128000,
        false,
        false,
        false,
        true,
    ),
    ("inkling", "Inkling", 1000000, true, true, true, true),
    ("kimi-k2-5", "Kimi K2.5", 256000, true, true, true, true),
    ("kimi-k2-6", "Kimi K2.6", 256000, true, true, true, true),
    (
        "kimi-k2-7-code",
        "Kimi K2.7 Code",
        256000,
        true,
        true,
        true,
        true,
    ),
    ("kimi-k3", "Kimi K3", 1000000, true, false, true, true),
    (
        "llama-3.2-3b",
        "Llama 3.2 3B",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "llama-3.3-70b",
        "Llama 3.3 70B",
        128000,
        false,
        false,
        true,
        true,
    ),
    ("mercury-2", "Mercury 2", 128000, true, true, true, true),
    (
        "minimax-m25",
        "MiniMax M2.5",
        198000,
        true,
        true,
        true,
        true,
    ),
    (
        "minimax-m27",
        "MiniMax M2.7",
        198000,
        true,
        true,
        true,
        true,
    ),
    (
        "minimax-m3-preview",
        "MiniMax M3 Preview",
        524288,
        true,
        false,
        true,
        true,
    ),
    (
        "mistral-small-2603",
        "Mistral Small 4",
        256000,
        true,
        true,
        true,
        true,
    ),
    (
        "mistral-small-3-2-24b-instruct",
        "Mistral Small 3.2 24B Instruct",
        256000,
        false,
        false,
        true,
        true,
    ),
    (
        "nvidia-nemotron-3-nano-30b-a3b",
        "NVIDIA Nemotron 3 Nano 30B",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "nvidia-nemotron-3-ultra-550b-a55b",
        "NVIDIA Nemotron 3 Ultra",
        256000,
        true,
        true,
        true,
        true,
    ),
    (
        "olafangensan-glm-4.7-flash-heretic",
        "GLM 4.7 Flash Heretic",
        200000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-4o-2024-11-20",
        "GPT-4o",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "openai-gpt-4o-mini-2024-07-18",
        "GPT-4o Mini",
        128000,
        false,
        false,
        true,
        true,
    ),
    ("openai-gpt-52", "GPT-5.2", 256000, true, true, true, true),
    (
        "openai-gpt-52-codex",
        "GPT-5.2 Codex",
        256000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-53-codex",
        "GPT-5.3 Codex",
        400000,
        true,
        true,
        true,
        true,
    ),
    ("openai-gpt-54", "GPT-5.4", 1000000, true, true, true, true),
    (
        "openai-gpt-54-mini",
        "GPT-5.4 Mini",
        400000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-54-pro",
        "GPT-5.4 Pro",
        1000000,
        true,
        true,
        true,
        true,
    ),
    ("openai-gpt-55", "GPT-5.5", 1000000, true, true, true, true),
    (
        "openai-gpt-55-pro",
        "GPT-5.5 Pro",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-56-luna",
        "GPT-5.6 Luna",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-56-luna-pro",
        "GPT-5.6 Luna Pro",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-56-sol",
        "GPT-5.6 Sol",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-56-sol-pro",
        "GPT-5.6 Sol Pro",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-56-terra",
        "GPT-5.6 Terra",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-56-terra-pro",
        "GPT-5.6 Terra Pro",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "openai-gpt-oss-120b",
        "OpenAI GPT OSS 120B",
        128000,
        true,
        true,
        true,
        true,
    ),
    (
        "qwen-3-6-plus",
        "Qwen 3.6 Plus Uncensored",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "qwen-3-7-max",
        "Qwen 3.7 Max",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "qwen-3-7-plus",
        "Qwen 3.7 Plus",
        1000000,
        true,
        false,
        true,
        true,
    ),
    (
        "qwen3-235b-a22b-instruct-2507",
        "Qwen 3 235B A22B Instruct 2507",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "qwen3-235b-a22b-thinking-2507",
        "Qwen 3 235B A22B Thinking 2507",
        128000,
        true,
        true,
        true,
        true,
    ),
    (
        "qwen3-5-35b-a3b",
        "Qwen 3.5 35B A3B",
        256000,
        true,
        true,
        true,
        true,
    ),
    (
        "qwen3-5-397b-a17b",
        "Qwen 3.5 397B",
        128000,
        true,
        true,
        true,
        true,
    ),
    ("qwen3-5-9b", "Qwen 3.5 9B", 256000, true, true, true, true),
    (
        "qwen3-6-27b",
        "Qwen 3.6 27B",
        256000,
        true,
        true,
        true,
        true,
    ),
    (
        "qwen3-6-35b-a3b",
        "Qwen 3.6 35B A3B",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "qwen3-coder-480b-a35b-instruct-turbo",
        "Qwen 3 Coder 480B Turbo",
        256000,
        false,
        false,
        true,
        true,
    ),
    (
        "qwen3-next-80b",
        "Qwen 3 Next 80b",
        256000,
        false,
        false,
        true,
        true,
    ),
    (
        "qwen3-vl-235b-a22b",
        "Qwen3 VL 235B",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "seed-2-1-turbo",
        "Seed 2.1 Turbo",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "venice-uncensored-1-2",
        "Venice Uncensored 1.2",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "venice-uncensored-role-play",
        "Venice Role Play Uncensored",
        128000,
        false,
        false,
        true,
        true,
    ),
    (
        "xiaomi-mimo-v2-5",
        "MiMo-V2.5",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "z-ai-glm-5-turbo",
        "GLM 5 Turbo",
        200000,
        true,
        true,
        true,
        true,
    ),
    (
        "z-ai-glm-5v-turbo",
        "GLM 5V Turbo",
        200000,
        true,
        true,
        true,
        true,
    ),
    ("zai-org-glm-4.6", "GLM 4.6", 198000, true, true, true, true),
    ("zai-org-glm-4.7", "GLM 4.7", 198000, true, true, true, true),
    (
        "zai-org-glm-4.7-flash",
        "GLM 4.7 Flash",
        128000,
        true,
        true,
        true,
        true,
    ),
    ("zai-org-glm-5", "GLM 5", 198000, true, true, true, true),
    ("zai-org-glm-5-1", "GLM 5.1", 200000, true, true, true, true),
    (
        "zai-org-glm-5-2",
        "GLM 5.2",
        1000000,
        true,
        false,
        true,
        true,
    ),
];

/// volcengine: 3 models (3 unverified).
pub static VOLCENGINE_MODELS: &[CatalogRow] = &[
    (
        "deepseek-v3-2-251201",
        "DeepSeek V3.2",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "doubao-seed-1-8-251228",
        "Doubao Seed 1.8",
        256000,
        false,
        false,
        true,
        false,
    ),
    (
        "kimi-k2-5-260127",
        "Kimi K2.5",
        256000,
        false,
        false,
        true,
        false,
    ),
];

/// xai: 5 models (0 unverified).
pub static XAI_MODELS: &[CatalogRow] = &[
    ("grok-4.20", "Grok 4.20", 2000000, true, false, true, true),
    (
        "grok-4.20-multi-agent",
        "Grok 4.20 Multi-Agent",
        2000000,
        true,
        true,
        false,
        true,
    ),
    ("grok-4.3", "Grok 4.3", 1000000, true, true, true, true),
    ("grok-4.5", "Grok 4.5", 500000, true, true, true, true),
    (
        "grok-build-0.1",
        "Grok Build 0.1",
        256000,
        true,
        false,
        true,
        true,
    ),
];

/// xiaomi: 3 models (3 unverified).
pub static XIAOMI_MODELS: &[CatalogRow] = &[
    (
        "mimo-v2-flash",
        "MiMo V2 Flash (free)",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "mimo-v2-omni",
        "MiMo V2 Omni",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "mimo-v2-pro",
        "MiMo V2 Pro",
        1048576,
        true,
        false,
        true,
        false,
    ),
];

/// zai: 6 models (1 unverified).
pub static ZAI_MODELS: &[CatalogRow] = &[
    (
        "glm-4.5-flash",
        "GLM-4.5 Flash (free)",
        131072,
        true,
        false,
        true,
        false,
    ),
    ("glm-4.6", "GLM-4.6", 204800, true, false, true, true),
    ("glm-4.7", "GLM-4.7", 204800, true, false, true, true),
    (
        "glm-4.7-flash",
        "GLM-4.7 Flash",
        202752,
        true,
        false,
        true,
        true,
    ),
    ("glm-5", "GLM-5", 202752, true, false, true, true),
    ("glm-5.1", "GLM-5.1", 204800, true, false, true, true),
];

/// Every generated table, keyed by provider id.
pub fn table_for(provider_id: &str) -> Option<&'static [CatalogRow]> {
    Some(match provider_id {
        "anthropic" => ANTHROPIC_MODELS,
        "byteplus" => BYTEPLUS_MODELS,
        "cerebras" => CEREBRAS_MODELS,
        "chutes" => CHUTES_MODELS,
        "deepinfra" => DEEPINFRA_MODELS,
        "deepseek" => DEEPSEEK_MODELS,
        "github-copilot" => GITHUB_COPILOT_MODELS,
        "google" => GOOGLE_MODELS,
        "google-gemini-cli" => GOOGLE_GEMINI_CLI_MODELS,
        "grok-cli" => GROK_CLI_MODELS,
        "groq" => GROQ_MODELS,
        "huggingface" => HUGGINGFACE_MODELS,
        "kilocode" => KILOCODE_MODELS,
        "kimi-coding" => KIMI_CODING_MODELS,
        "meta" => META_MODELS,
        "minimax-portal" => MINIMAX_PORTAL_MODELS,
        "mistral" => MISTRAL_MODELS,
        "moonshot" => MOONSHOT_MODELS,
        "nvidia" => NVIDIA_MODELS,
        "ollama" => OLLAMA_MODELS,
        "ollama-cloud" => OLLAMA_CLOUD_MODELS,
        "openai" => OPENAI_MODELS,
        "opencode" => OPENCODE_MODELS,
        "qianfan" => QIANFAN_MODELS,
        "stepfun" => STEPFUN_MODELS,
        "tencent" => TENCENT_MODELS,
        "together" => TOGETHER_MODELS,
        "venice" => VENICE_MODELS,
        "volcengine" => VOLCENGINE_MODELS,
        "xai" => XAI_MODELS,
        "xiaomi" => XIAOMI_MODELS,
        "zai" => ZAI_MODELS,
        _ => return None,
    })
}

/// Does this (provider, model) accept a named reasoning effort?
pub fn takes_effort(provider_id: &str, model_id: &str) -> Option<bool> {
    row(provider_id, model_id).map(|r| r.4)
}

/// Can this (provider, model) call tools? A turn only ends when the model calls
/// `final_answer`, so a lane assigned a no-tools model can never finish one.
pub fn supports_tools(provider_id: &str, model_id: &str) -> Option<bool> {
    row(provider_id, model_id).map(|r| r.5)
}

/// Is this row's metadata sourced, or is it a fallback carrying a default?
pub fn is_verified(provider_id: &str, model_id: &str) -> Option<bool> {
    row(provider_id, model_id).map(|r| r.6)
}

fn row(provider_id: &str, model_id: &str) -> Option<&'static CatalogRow> {
    table_for(provider_id)?.iter().find(|r| r.0 == model_id)
}
