//! The OpenRouter model catalog — generated from the live
//! `https://openrouter.ai/api/v1/models` response (fetched 2026-07-29).
//!
//! WHY THIS IS A GENERATED TABLE AND NOT A HAND-PICKED SHORTLIST
//!
//! OpenRouter is an aggregator: its ids (`vendor/model[:tier]`) are the ONLY
//! names the API answers to, and the same base model carries a DIFFERENT
//! context window per tier. `nvidia/nemotron-3-ultra-550b-a55b` is 512288
//! tokens; the `:free` tier of that same model is 1000000. Resolving a tier
//! suffix by stripping it and matching the base therefore produces the WRONG
//! window — which is why every entry here is listed at its full id.
//!
//! `effort` is not a guess either: it mirrors `reasoning_effort` in the
//! model's `supported_parameters`. A model that does not advertise it must not
//! be handed an effort ladder, or the UI grows a control the API ignores.
//!
//! `tools` mirrors `tools` in `supported_parameters`. A model without it
//! cannot call a tool at all — and since a Phoenix turn only ends when the
//! model calls `final_answer`, assigning a no-tools model to an agent lane
//! produces exactly the "it wrote prose and then just stopped" failure.

/// `(id, display name, context window, reasoning, takes reasoning_effort, tool calling, free tier)`
pub type OpenRouterModel = (&'static str, &'static str, u32, bool, bool, bool, bool);

pub static OPENROUTER_MODELS: &[OpenRouterModel] = &[
    (
        "ai21/jamba-large-1.7",
        "Jamba Large 1.7",
        256000,
        false,
        false,
        true,
        false,
    ),
    (
        "aion-labs/aion-2.0",
        "Aion-2.0",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "aion-labs/aion-3.0",
        "Aion-3.0",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "aion-labs/aion-3.0-mini",
        "Aion-3.0-Mini",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "aion-labs/aion-rp-llama-3.1-8b",
        "Aion-RP 1.0 (8B)",
        32768,
        false,
        false,
        false,
        false,
    ),
    (
        "allenai/olmo-3-32b-think",
        "Olmo 3 32B Think",
        65536,
        true,
        false,
        false,
        false,
    ),
    (
        "amazon/nova-2-lite-v1",
        "Nova 2 Lite",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "amazon/nova-lite-v1",
        "Nova Lite 1.0",
        300000,
        false,
        false,
        true,
        false,
    ),
    (
        "amazon/nova-micro-v1",
        "Nova Micro 1.0",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "amazon/nova-premier-v1",
        "Nova Premier 1.0",
        1000000,
        false,
        false,
        true,
        false,
    ),
    (
        "amazon/nova-pro-v1",
        "Nova Pro 1.0",
        300000,
        false,
        false,
        true,
        false,
    ),
    (
        "anthracite-org/magnum-v4-72b",
        "Magnum v4 72B",
        16384,
        false,
        false,
        false,
        false,
    ),
    (
        "anthropic/claude-3-haiku",
        "Claude 3 Haiku",
        200000,
        false,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-fable-5",
        "Claude Fable 5",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-fable-5:batch",
        "Claude Fable 5 (batch)",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-haiku-4.5",
        "Claude Haiku 4.5",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-haiku-4.5:batch",
        "Claude Haiku 4.5 (batch)",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4",
        "Claude Opus 4",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.1",
        "Claude Opus 4.1",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.1:batch",
        "Claude Opus 4.1 (batch)",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.5",
        "Claude Opus 4.5",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.5:batch",
        "Claude Opus 4.5 (batch)",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.6",
        "Claude Opus 4.6",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.6:batch",
        "Claude Opus 4.6 (batch)",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.7",
        "Claude Opus 4.7",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.7-fast",
        "Claude Opus 4.7 (Fast)",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.7:batch",
        "Claude Opus 4.7 (batch)",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.8",
        "Claude Opus 4.8",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.8-fast",
        "Claude Opus 4.8 (Fast)",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-4.8:batch",
        "Claude Opus 4.8 (batch)",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-5",
        "Claude Opus 5",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-opus-5-fast",
        "Claude Opus 5 (Fast)",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-sonnet-4",
        "Claude Sonnet 4",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-sonnet-4.5",
        "Claude Sonnet 4.5",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-sonnet-4.5:batch",
        "Claude Sonnet 4.5 (batch)",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "anthropic/claude-sonnet-4.6",
        "Claude Sonnet 4.6",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-sonnet-5",
        "Claude Sonnet 5",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "anthropic/claude-sonnet-5:batch",
        "Claude Sonnet 5 (batch)",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "arcee-ai/trinity-large-thinking",
        "Trinity Large Thinking",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "arcee-ai/virtuoso-large",
        "Virtuoso Large",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "baidu/ernie-4.5-vl-424b-a47b",
        "ERNIE 4.5 VL 424B A47B ",
        123000,
        true,
        false,
        false,
        false,
    ),
    (
        "bytedance-seed/seed-1.6",
        "Seed 1.6",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "bytedance-seed/seed-1.6-flash",
        "Seed 1.6 Flash",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "bytedance-seed/seed-2.0-lite",
        "Seed-2.0-Lite",
        262144,
        true,
        true,
        true,
        false,
    ),
    (
        "bytedance-seed/seed-2.0-mini",
        "Seed-2.0-Mini",
        262144,
        true,
        true,
        true,
        false,
    ),
    (
        "bytedance/ui-tars-1.5-7b",
        "UI-TARS 7B ",
        128000,
        false,
        false,
        false,
        false,
    ),
    (
        "cognitivecomputations/dolphin-mistral-24b-venice-edition",
        "Uncensored",
        128000,
        false,
        false,
        false,
        false,
    ),
    (
        "cohere/command-a",
        "Command A",
        256000,
        false,
        false,
        false,
        false,
    ),
    (
        "cohere/command-r-08-2024",
        "Command R (08-2024)",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "cohere/command-r-plus-08-2024",
        "Command R+ (08-2024)",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "cohere/command-r7b-12-2024",
        "Command R7B (12-2024)",
        128000,
        false,
        false,
        false,
        false,
    ),
    (
        "cohere/north-mini-code:free",
        "North Mini Code (free)",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "deepcogito/cogito-v2.1-671b",
        "Cogito v2.1 671B",
        128000,
        true,
        false,
        false,
        false,
    ),
    (
        "deepseek/deepseek-chat",
        "DeepSeek V3",
        163840,
        false,
        false,
        true,
        false,
    ),
    (
        "deepseek/deepseek-chat-v3-0324",
        "DeepSeek V3 0324",
        163840,
        false,
        false,
        true,
        false,
    ),
    (
        "deepseek/deepseek-chat-v3.1",
        "DeepSeek V3.1",
        163840,
        true,
        false,
        true,
        false,
    ),
    (
        "deepseek/deepseek-r1",
        "R1",
        163840,
        true,
        false,
        true,
        false,
    ),
    (
        "deepseek/deepseek-r1-0528",
        "R1 0528",
        163840,
        true,
        false,
        true,
        false,
    ),
    (
        "deepseek/deepseek-r1-distill-llama-70b",
        "R1 Distill Llama 70B",
        8192,
        true,
        false,
        false,
        false,
    ),
    (
        "deepseek/deepseek-v3.1-terminus",
        "DeepSeek V3.1 Terminus",
        163840,
        true,
        false,
        true,
        false,
    ),
    (
        "deepseek/deepseek-v3.2",
        "DeepSeek V3.2",
        163840,
        true,
        false,
        true,
        false,
    ),
    (
        "deepseek/deepseek-v3.2-exp",
        "DeepSeek V3.2 Exp",
        163840,
        true,
        false,
        true,
        false,
    ),
    (
        "deepseek/deepseek-v4-flash",
        "DeepSeek V4 Flash",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "deepseek/deepseek-v4-pro",
        "DeepSeek V4 Pro",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-2.5-flash",
        "Gemini 2.5 Flash",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemini-2.5-flash-image",
        "Nano Banana (Gemini 2.5 Flash Image)",
        32768,
        false,
        false,
        false,
        false,
    ),
    (
        "google/gemini-2.5-flash-lite",
        "Gemini 2.5 Flash Lite",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemini-2.5-flash-lite:batch",
        "Gemini 2.5 Flash Lite (batch)",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemini-2.5-flash:batch",
        "Gemini 2.5 Flash (batch)",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemini-2.5-pro",
        "Gemini 2.5 Pro",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemini-2.5-pro-preview",
        "Gemini 2.5 Pro Preview 06-05",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemini-2.5-pro-preview-05-06",
        "Gemini 2.5 Pro Preview 05-06",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemini-2.5-pro:batch",
        "Gemini 2.5 Pro (batch)",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemini-3-flash-preview",
        "Gemini 3 Flash Preview",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3-flash-preview:batch",
        "Gemini 3 Flash Preview (batch)",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3-pro-image",
        "Nano Banana Pro (Gemini 3 Pro Image)",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemini-3-pro-image-preview",
        "Nano Banana Pro (Gemini 3 Pro Image Preview)",
        65536,
        true,
        false,
        false,
        false,
    ),
    (
        "google/gemini-3.1-flash-image",
        "Nano Banana 2 (Gemini 3.1 Flash Image)",
        131072,
        true,
        true,
        false,
        false,
    ),
    (
        "google/gemini-3.1-flash-image-preview",
        "Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
        65536,
        true,
        true,
        false,
        false,
    ),
    (
        "google/gemini-3.1-flash-lite",
        "Gemini 3.1 Flash Lite",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.1-flash-lite-image",
        "Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
        65536,
        true,
        true,
        false,
        false,
    ),
    (
        "google/gemini-3.1-flash-lite-preview",
        "Gemini 3.1 Flash Lite Preview",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.1-flash-lite:batch",
        "Gemini 3.1 Flash Lite (batch)",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.1-pro-preview",
        "Gemini 3.1 Pro Preview",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.1-pro-preview-customtools",
        "Gemini 3.1 Pro Preview Custom Tools",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.1-pro-preview:batch",
        "Gemini 3.1 Pro Preview (batch)",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.5-flash",
        "Gemini 3.5 Flash",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.5-flash-lite",
        "Gemini 3.5 Flash Lite",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.5-flash-lite:batch",
        "Gemini 3.5 Flash Lite (batch)",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.5-flash:batch",
        "Gemini 3.5 Flash (batch)",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.6-flash",
        "Gemini 3.6 Flash",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemini-3.6-flash:batch",
        "Gemini 3.6 Flash (batch)",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "google/gemma-2-27b-it",
        "Gemma 2 27B",
        8192,
        false,
        false,
        false,
        false,
    ),
    (
        "google/gemma-3-12b-it",
        "Gemma 3 12B",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "google/gemma-3-27b-it",
        "Gemma 3 27B",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "google/gemma-3-4b-it",
        "Gemma 3 4B",
        131072,
        false,
        false,
        false,
        false,
    ),
    (
        "google/gemma-3n-e4b-it",
        "Gemma 3n 4B",
        32768,
        false,
        false,
        false,
        false,
    ),
    (
        "google/gemma-4-26b-a4b-it",
        "Gemma 4 26B A4B ",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemma-4-26b-a4b-it:free",
        "Gemma 4 26B A4B  (free)",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "google/gemma-4-31b-it",
        "Gemma 4 31B",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "google/gemma-4-31b-it:free",
        "Gemma 4 31B (free)",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "google/lyria-3-clip-preview",
        "Lyria 3 Clip Preview",
        1048576,
        false,
        false,
        false,
        true,
    ),
    (
        "google/lyria-3-pro-preview",
        "Lyria 3 Pro Preview",
        1048576,
        false,
        false,
        false,
        true,
    ),
    (
        "gryphe/mythomax-l2-13b",
        "MythoMax 13B",
        8192,
        false,
        false,
        false,
        false,
    ),
    (
        "ibm-granite/granite-4.0-h-micro",
        "Granite 4.0 Micro",
        131000,
        false,
        false,
        false,
        false,
    ),
    (
        "ibm-granite/granite-4.1-8b",
        "Granite 4.1 8B",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "inception/mercury-2",
        "Mercury 2",
        128000,
        true,
        true,
        true,
        false,
    ),
    (
        "inclusionai/ling-2.6-1t",
        "Ling-2.6-1T",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "inclusionai/ling-2.6-flash",
        "Ling-2.6-flash",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "inclusionai/ling-3.0-flash:free",
        "Ling-3.0-flash (free)",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "inclusionai/ring-2.6-1t",
        "Ring-2.6-1T",
        262144,
        true,
        true,
        true,
        false,
    ),
    (
        "kwaipilot/kat-coder-air-v2.5",
        "KAT-Coder-Air V2.5",
        256000,
        false,
        false,
        true,
        false,
    ),
    (
        "kwaipilot/kat-coder-pro-v2",
        "KAT-Coder-Pro V2",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "kwaipilot/kat-coder-pro-v2.5",
        "KAT-Coder-Pro V2.5",
        256000,
        false,
        false,
        true,
        false,
    ),
    (
        "mancer/weaver",
        "Weaver (alpha)",
        8000,
        false,
        false,
        false,
        false,
    ),
    (
        "meituan/longcat-2.0",
        "LongCat 2.0",
        1048756,
        true,
        false,
        true,
        false,
    ),
    (
        "meta-llama/llama-3.1-70b-instruct",
        "Llama 3.1 70B Instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "meta-llama/llama-3.1-8b-instruct",
        "Llama 3.1 8B Instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "meta-llama/llama-3.2-1b-instruct",
        "Llama 3.2 1B Instruct",
        60000,
        false,
        false,
        false,
        false,
    ),
    (
        "meta-llama/llama-3.2-3b-instruct",
        "Llama 3.2 3B Instruct",
        131072,
        false,
        false,
        false,
        false,
    ),
    (
        "meta-llama/llama-3.3-70b-instruct",
        "Llama 3.3 70B Instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "meta-llama/llama-4-maverick",
        "Llama 4 Maverick",
        1048576,
        false,
        false,
        true,
        false,
    ),
    (
        "meta-llama/llama-4-scout",
        "Llama 4 Scout",
        1310720,
        false,
        false,
        true,
        false,
    ),
    (
        "meta-llama/llama-guard-4-12b",
        "Llama Guard 4 12B",
        1048576,
        false,
        false,
        false,
        false,
    ),
    (
        "meta/muse-spark-1.1",
        "Muse Spark 1.1",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "microsoft/phi-4",
        "Phi 4",
        16384,
        false,
        false,
        false,
        false,
    ),
    (
        "microsoft/wizardlm-2-8x22b",
        "WizardLM-2 8x22B",
        65535,
        false,
        false,
        false,
        false,
    ),
    (
        "minimax/minimax-01",
        "MiniMax-01",
        1000192,
        false,
        false,
        false,
        false,
    ),
    (
        "minimax/minimax-m1",
        "MiniMax M1",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "minimax/minimax-m2",
        "MiniMax M2",
        204800,
        true,
        false,
        true,
        false,
    ),
    (
        "minimax/minimax-m2-her",
        "MiniMax M2-her",
        65536,
        false,
        false,
        false,
        false,
    ),
    (
        "minimax/minimax-m2.1",
        "MiniMax M2.1",
        204800,
        true,
        false,
        true,
        false,
    ),
    (
        "minimax/minimax-m2.5",
        "MiniMax M2.5",
        204800,
        true,
        false,
        true,
        false,
    ),
    (
        "minimax/minimax-m2.7",
        "MiniMax M2.7",
        204800,
        true,
        false,
        true,
        false,
    ),
    (
        "minimax/minimax-m3",
        "MiniMax M3",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "minimax/minimax-m3:batch",
        "MiniMax M3 (batch)",
        524288,
        true,
        false,
        true,
        false,
    ),
    (
        "mistralai/codestral-2508",
        "Codestral 2508",
        256000,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/devstral-2512",
        "Devstral 2 2512",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/ministral-14b-2512",
        "Ministral 3 14B 2512",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/ministral-3b-2512",
        "Ministral 3 3B 2512",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/ministral-8b-2512",
        "Ministral 3 8B 2512",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-large",
        "Mistral Large",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-large-2407",
        "Mistral Large 2407",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-large-2512",
        "Mistral Large 3 2512",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-medium-3",
        "Mistral Medium 3",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-medium-3-5",
        "Mistral Medium 3.5",
        262144,
        true,
        true,
        true,
        false,
    ),
    (
        "mistralai/mistral-medium-3.1",
        "Mistral Medium 3.1",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-nemo",
        "Mistral Nemo",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-saba",
        "Saba",
        32768,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mistral-small-24b-instruct-2501",
        "Mistral Small 3",
        32768,
        false,
        false,
        false,
        false,
    ),
    (
        "mistralai/mistral-small-2603",
        "Mistral Small 4",
        262144,
        true,
        true,
        true,
        false,
    ),
    (
        "mistralai/mistral-small-3.1-24b-instruct",
        "Mistral Small 3.1 24B",
        128000,
        false,
        false,
        false,
        false,
    ),
    (
        "mistralai/mistral-small-3.2-24b-instruct",
        "Mistral Small 3.2 24B",
        256000,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/mixtral-8x22b-instruct",
        "Mixtral 8x22B Instruct",
        65536,
        false,
        false,
        true,
        false,
    ),
    (
        "mistralai/voxtral-small-24b-2507",
        "Voxtral Small 24B 2507",
        32000,
        false,
        false,
        true,
        false,
    ),
    (
        "moonshotai/kimi-k2",
        "Kimi K2 0711",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "moonshotai/kimi-k2-0905",
        "Kimi K2 0905",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "moonshotai/kimi-k2-thinking",
        "Kimi K2 Thinking",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "moonshotai/kimi-k2.5",
        "Kimi K2.5",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "moonshotai/kimi-k2.6",
        "Kimi K2.6",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "moonshotai/kimi-k2.7-code",
        "Kimi K2.7 Code",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "moonshotai/kimi-k3",
        "Kimi K3",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "morph/morph-v3-fast",
        "Morph V3 Fast",
        81920,
        false,
        false,
        false,
        false,
    ),
    (
        "morph/morph-v3-large",
        "Morph V3 Large",
        262144,
        false,
        false,
        false,
        false,
    ),
    (
        "nex-agi/nex-n2-mini",
        "Nex-N2-Mini",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "nex-agi/nex-n2-pro",
        "Nex-N2-Pro",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "nousresearch/hermes-3-llama-3.1-405b",
        "Hermes 3 405B Instruct",
        131072,
        false,
        false,
        false,
        false,
    ),
    (
        "nousresearch/hermes-3-llama-3.1-70b",
        "Hermes 3 70B Instruct",
        131072,
        false,
        false,
        false,
        false,
    ),
    (
        "nousresearch/hermes-4-405b",
        "Hermes 4 405B",
        131072,
        true,
        false,
        false,
        false,
    ),
    (
        "nousresearch/hermes-4-70b",
        "Hermes 4 70B",
        131072,
        true,
        false,
        false,
        false,
    ),
    (
        "nvidia/nemotron-3-nano-30b-a3b",
        "Nemotron 3 Nano 30B A3B",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "nvidia/nemotron-3-nano-30b-a3b:free",
        "Nemotron 3 Nano 30B A3B (free)",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
        "Nemotron 3 Nano Omni (free)",
        256000,
        true,
        false,
        true,
        true,
    ),
    (
        "nvidia/nemotron-3-super-120b-a12b",
        "Nemotron 3 Super",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "nvidia/nemotron-3-super-120b-a12b:free",
        "Nemotron 3 Super (free)",
        262144,
        true,
        true,
        true,
        true,
    ),
    (
        "nvidia/nemotron-3-ultra-550b-a55b",
        "Nemotron 3 Ultra",
        512288,
        true,
        true,
        true,
        false,
    ),
    (
        "nvidia/nemotron-3-ultra-550b-a55b:free",
        "Nemotron 3 Ultra (free)",
        1000000,
        true,
        true,
        true,
        true,
    ),
    (
        "nvidia/nemotron-3.5-content-safety:free",
        "Nemotron 3.5 Content Safety (free)",
        128000,
        true,
        false,
        false,
        true,
    ),
    (
        "nvidia/nemotron-nano-12b-v2-vl:free",
        "Nemotron Nano 12B 2 VL (free)",
        128000,
        true,
        false,
        true,
        true,
    ),
    (
        "nvidia/nemotron-nano-9b-v2:free",
        "Nemotron Nano 9B V2 (free)",
        128000,
        true,
        false,
        true,
        true,
    ),
    (
        "openai/gpt-3.5-turbo",
        "GPT-3.5 Turbo",
        16385,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-3.5-turbo-0613",
        "GPT-3.5 Turbo (older v0613)",
        4095,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-3.5-turbo-16k",
        "GPT-3.5 Turbo 16k",
        16385,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-3.5-turbo-instruct",
        "GPT-3.5 Turbo Instruct",
        4095,
        false,
        false,
        false,
        false,
    ),
    ("openai/gpt-4", "GPT-4", 8191, false, false, true, false),
    (
        "openai/gpt-4-turbo",
        "GPT-4 Turbo",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-4-turbo-preview",
        "GPT-4 Turbo Preview",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-4.1",
        "GPT-4.1",
        1047576,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-4.1-mini",
        "GPT-4.1 Mini",
        1047576,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-4.1-nano",
        "GPT-4.1 Nano",
        1047576,
        false,
        false,
        true,
        false,
    ),
    ("openai/gpt-4o", "GPT-4o", 128000, false, false, true, false),
    (
        "openai/gpt-4o-2024-05-13",
        "GPT-4o (2024-05-13)",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-4o-2024-08-06",
        "GPT-4o (2024-08-06)",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-4o-2024-11-20",
        "GPT-4o (2024-11-20)",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-4o-mini",
        "GPT-4o-mini",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-4o-mini-2024-07-18",
        "GPT-4o-mini (2024-07-18)",
        128000,
        false,
        false,
        true,
        false,
    ),
    ("openai/gpt-5", "GPT-5", 400000, true, true, true, false),
    (
        "openai/gpt-5-codex",
        "GPT-5 Codex",
        400000,
        true,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-5-image",
        "GPT-5 Image",
        400000,
        true,
        false,
        false,
        false,
    ),
    (
        "openai/gpt-5-image-mini",
        "GPT-5 Image Mini",
        400000,
        true,
        false,
        false,
        false,
    ),
    (
        "openai/gpt-5-mini",
        "GPT-5 Mini",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5-mini:batch",
        "GPT-5 Mini (batch)",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5-nano",
        "GPT-5 Nano",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5-nano:batch",
        "GPT-5 Nano (batch)",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5-pro",
        "GPT-5 Pro",
        400000,
        true,
        true,
        true,
        false,
    ),
    ("openai/gpt-5.1", "GPT-5.1", 400000, true, true, true, false),
    (
        "openai/gpt-5.1-chat",
        "GPT-5.1 Chat",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-5.1-codex",
        "GPT-5.1-Codex",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.1-codex-max",
        "GPT-5.1-Codex-Max",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.1-codex-mini",
        "GPT-5.1-Codex-Mini",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.1:batch",
        "GPT-5.1 (batch)",
        400000,
        true,
        true,
        true,
        false,
    ),
    ("openai/gpt-5.2", "GPT-5.2", 400000, true, true, true, false),
    (
        "openai/gpt-5.2-chat",
        "GPT-5.2 Chat",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-5.2-codex",
        "GPT-5.2-Codex",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.2-pro",
        "GPT-5.2 Pro",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.2:batch",
        "GPT-5.2 (batch)",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.3-chat",
        "GPT-5.3 Chat",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-5.3-codex",
        "GPT-5.3-Codex",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.4",
        "GPT-5.4",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.4-image-2",
        "GPT-5.4 Image 2",
        272000,
        true,
        true,
        false,
        false,
    ),
    (
        "openai/gpt-5.4-mini",
        "GPT-5.4 Mini",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.4-mini:batch",
        "GPT-5.4 Mini (batch)",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.4-nano",
        "GPT-5.4 Nano",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.4-nano:batch",
        "GPT-5.4 Nano (batch)",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.4-pro",
        "GPT-5.4 Pro",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.4:batch",
        "GPT-5.4 (batch)",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.5",
        "GPT-5.5",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.5-pro",
        "GPT-5.5 Pro",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.5:batch",
        "GPT-5.5 (batch)",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.6-luna",
        "GPT-5.6 Luna",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.6-luna-pro",
        "GPT-5.6 Luna Pro",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.6-sol",
        "GPT-5.6 Sol",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.6-sol-pro",
        "GPT-5.6 Sol Pro",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.6-terra",
        "GPT-5.6 Terra",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5.6-terra-pro",
        "GPT-5.6 Terra Pro",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-5:batch",
        "GPT-5 (batch)",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-audio",
        "GPT Audio",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-audio-mini",
        "GPT Audio Mini",
        128000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-chat-latest",
        "GPT Chat Latest",
        400000,
        false,
        false,
        true,
        false,
    ),
    (
        "openai/gpt-oss-120b",
        "gpt-oss-120b",
        131072,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-oss-20b",
        "gpt-oss-20b",
        131072,
        true,
        true,
        true,
        false,
    ),
    (
        "openai/gpt-oss-20b:free",
        "gpt-oss-20b (free)",
        131072,
        true,
        true,
        true,
        true,
    ),
    (
        "openai/gpt-oss-safeguard-20b",
        "gpt-oss-safeguard-20b",
        131072,
        true,
        false,
        true,
        false,
    ),
    ("openai/o1", "o1", 200000, true, false, true, false),
    ("openai/o1-pro", "o1-pro", 200000, true, false, false, false),
    ("openai/o3", "o3", 200000, true, false, true, false),
    (
        "openai/o3-deep-research",
        "o3 Deep Research",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "openai/o3-mini",
        "o3 Mini",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "openai/o3-mini-high",
        "o3 Mini High",
        200000,
        true,
        true,
        true,
        false,
    ),
    ("openai/o3-pro", "o3 Pro", 200000, true, false, true, false),
    (
        "openai/o4-mini",
        "o4 Mini",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "openai/o4-mini-deep-research",
        "o4 Mini Deep Research",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "openai/o4-mini-high",
        "o4 Mini High",
        200000,
        true,
        true,
        true,
        false,
    ),
    (
        "openrouter/auto",
        "Auto Router",
        2000000,
        true,
        true,
        true,
        false,
    ),
    (
        "openrouter/auto-beta",
        "Auto Router (Beta)",
        2000000,
        true,
        true,
        true,
        false,
    ),
    (
        "openrouter/bodybuilder",
        "Body Builder (beta)",
        128000,
        false,
        false,
        false,
        false,
    ),
    (
        "openrouter/free",
        "Free Models Router",
        200000,
        true,
        true,
        true,
        true,
    ),
    (
        "openrouter/fusion",
        "Fusion",
        1000000,
        false,
        false,
        false,
        false,
    ),
    (
        "openrouter/pareto-code",
        "Pareto Code Router",
        2000000,
        false,
        false,
        false,
        false,
    ),
    (
        "perceptron/perceptron-mk1",
        "Perceptron Mk1",
        32768,
        true,
        false,
        false,
        false,
    ),
    (
        "perplexity/sonar",
        "Sonar",
        127072,
        false,
        false,
        false,
        false,
    ),
    (
        "perplexity/sonar-deep-research",
        "Sonar Deep Research",
        128000,
        true,
        false,
        false,
        false,
    ),
    (
        "perplexity/sonar-pro",
        "Sonar Pro",
        200000,
        false,
        false,
        false,
        false,
    ),
    (
        "perplexity/sonar-pro-search",
        "Sonar Pro Search",
        200000,
        true,
        false,
        false,
        false,
    ),
    (
        "perplexity/sonar-reasoning-pro",
        "Sonar Reasoning Pro",
        128000,
        true,
        false,
        false,
        false,
    ),
    (
        "poolside/laguna-s-2.1",
        "Laguna S 2.1",
        1048576,
        true,
        false,
        true,
        false,
    ),
    (
        "poolside/laguna-s-2.1:free",
        "Laguna S 2.1 (free)",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "poolside/laguna-xs-2.1",
        "Laguna XS 2.1",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "poolside/laguna-xs-2.1:free",
        "Laguna XS 2.1 (free)",
        262144,
        true,
        false,
        true,
        true,
    ),
    (
        "qwen/qwen-2.5-72b-instruct",
        "Qwen2.5 72B Instruct",
        32768,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen-2.5-7b-instruct",
        "Qwen2.5 7B Instruct",
        32768,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen-2.5-coder-32b-instruct",
        "Qwen2.5 Coder 32B Instruct",
        32768,
        false,
        false,
        false,
        false,
    ),
    (
        "qwen/qwen-plus",
        "Qwen-Plus",
        1000000,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen-plus-2025-07-28",
        "Qwen Plus 0728",
        1000000,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen-plus-2025-07-28:thinking",
        "Qwen Plus 0728 (thinking)",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen2.5-vl-72b-instruct",
        "Qwen2.5 VL 72B Instruct",
        128000,
        false,
        false,
        false,
        false,
    ),
    (
        "qwen/qwen3-14b",
        "Qwen3 14B",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-235b-a22b",
        "Qwen3 235B A22B",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-235b-a22b-2507",
        "Qwen3 235B A22B Instruct 2507",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-235b-a22b-thinking-2507",
        "Qwen3 235B A22B Thinking 2507",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-30b-a3b",
        "Qwen3 30B A3B",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-30b-a3b-instruct-2507",
        "Qwen3 30B A3B Instruct 2507",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-30b-a3b-thinking-2507",
        "Qwen3 30B A3B Thinking 2507",
        81920,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-32b",
        "Qwen3 32B",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-8b",
        "Qwen3 8B",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-coder",
        "Qwen3 Coder 480B A35B",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-coder-30b-a3b-instruct",
        "Qwen3 Coder 30B A3B Instruct",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-coder-flash",
        "Qwen3 Coder Flash",
        1000000,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-coder-next",
        "Qwen3 Coder Next",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-coder-plus",
        "Qwen3 Coder Plus",
        1000000,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-max",
        "Qwen3 Max",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-max-thinking",
        "Qwen3 Max Thinking",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-next-80b-a3b-instruct",
        "Qwen3 Next 80B A3B Instruct",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-next-80b-a3b-thinking",
        "Qwen3 Next 80B A3B Thinking",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-vl-235b-a22b-instruct",
        "Qwen3 VL 235B A22B Instruct",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-vl-235b-a22b-thinking",
        "Qwen3 VL 235B A22B Thinking",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-vl-30b-a3b-instruct",
        "Qwen3 VL 30B A3B Instruct",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-vl-30b-a3b-thinking",
        "Qwen3 VL 30B A3B Thinking",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-vl-32b-instruct",
        "Qwen3 VL 32B Instruct",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-vl-8b-instruct",
        "Qwen3 VL 8B Instruct",
        262144,
        false,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3-vl-8b-thinking",
        "Qwen3 VL 8B Thinking",
        131072,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.5-122b-a10b",
        "Qwen3.5-122B-A10B",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.5-27b",
        "Qwen3.5-27B",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.5-35b-a3b",
        "Qwen3.5-35B-A3B",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.5-397b-a17b",
        "Qwen3.5 397B A17B",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.5-9b",
        "Qwen3.5-9B",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.5-flash-02-23",
        "Qwen3.5-Flash",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.5-plus-02-15",
        "Qwen3.5 Plus 2026-02-15",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.5-plus-20260420",
        "Qwen3.5 Plus 2026-04-20",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.6-27b",
        "Qwen3.6 27B",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.6-35b-a3b",
        "Qwen3.6 35B A3B",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.6-flash",
        "Qwen3.6 Flash",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.6-max-preview",
        "Qwen3.6 Max Preview",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.6-plus",
        "Qwen3.6 Plus",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.7-flash",
        "Qwen3.7 Flash",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.7-max",
        "Qwen3.7 Max",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "qwen/qwen3.7-plus",
        "Qwen3.7 Plus",
        1000000,
        true,
        false,
        true,
        false,
    ),
    (
        "rekaai/reka-edge",
        "Reka Edge",
        16384,
        false,
        false,
        true,
        false,
    ),
    (
        "rekaai/reka-flash-3",
        "Reka Flash 3",
        65536,
        true,
        false,
        false,
        false,
    ),
    (
        "relace/relace-apply-3",
        "Relace Apply 3",
        256000,
        false,
        false,
        false,
        false,
    ),
    (
        "relace/relace-search",
        "Relace Search",
        256000,
        false,
        false,
        true,
        false,
    ),
    (
        "sakana/fugu-ultra",
        "Fugu Ultra",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "sao10k/l3-lunaris-8b",
        "Llama 3 8B Lunaris",
        8192,
        false,
        false,
        false,
        false,
    ),
    (
        "sao10k/l3.1-euryale-70b",
        "Llama 3.1 Euryale 70B v2.2",
        131072,
        false,
        false,
        true,
        false,
    ),
    (
        "sao10k/l3.3-euryale-70b",
        "Llama 3.3 Euryale 70B",
        131072,
        false,
        false,
        false,
        false,
    ),
    (
        "stepfun/step-3.5-flash",
        "Step 3.5 Flash",
        262144,
        true,
        false,
        true,
        false,
    ),
    (
        "stepfun/step-3.7-flash",
        "Step 3.7 Flash",
        262144,
        true,
        true,
        true,
        false,
    ),
    (
        "tencent/hunyuan-a13b-instruct",
        "Hunyuan A13B Instruct",
        131072,
        true,
        false,
        false,
        false,
    ),
    ("tencent/hy3", "Hy3", 262144, true, true, true, false),
    (
        "tencent/hy3-preview",
        "Hy3 preview",
        262144,
        true,
        true,
        true,
        false,
    ),
    (
        "thedrummer/cydonia-24b-v4.1",
        "Cydonia 24B V4.1",
        131072,
        false,
        false,
        false,
        false,
    ),
    (
        "thedrummer/rocinante-12b",
        "Rocinante 12B",
        65536,
        false,
        false,
        false,
        false,
    ),
    (
        "thedrummer/skyfall-36b-v2",
        "Skyfall 36B V2",
        32768,
        false,
        false,
        false,
        false,
    ),
    (
        "thedrummer/unslopnemo-12b",
        "UnslopNemo 12B",
        32768,
        false,
        false,
        true,
        false,
    ),
    (
        "thinkingmachines/inkling",
        "Inkling",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "undi95/remm-slerp-l2-13b",
        "ReMM SLERP 13B",
        6144,
        false,
        false,
        false,
        false,
    ),
    (
        "upstage/solar-pro-3",
        "Solar Pro 3",
        128000,
        true,
        false,
        true,
        false,
    ),
    (
        "writer/palmyra-x5",
        "Palmyra X5",
        1040000,
        false,
        false,
        false,
        false,
    ),
    (
        "x-ai/grok-4.20",
        "Grok 4.20",
        2000000,
        true,
        false,
        true,
        false,
    ),
    (
        "x-ai/grok-4.20-multi-agent",
        "Grok 4.20 Multi-Agent",
        2000000,
        true,
        true,
        false,
        false,
    ),
    (
        "x-ai/grok-4.3",
        "Grok 4.3",
        1000000,
        true,
        true,
        true,
        false,
    ),
    ("x-ai/grok-4.5", "Grok 4.5", 500000, true, true, true, false),
    (
        "x-ai/grok-build-0.1",
        "Grok Build 0.1",
        256000,
        true,
        false,
        true,
        false,
    ),
    (
        "xiaomi/mimo-v2.5",
        "MiMo-V2.5",
        1050000,
        true,
        false,
        true,
        false,
    ),
    (
        "xiaomi/mimo-v2.5-pro",
        "MiMo-V2.5-Pro",
        1050000,
        true,
        false,
        true,
        false,
    ),
    ("z-ai/glm-4.5", "GLM 4.5", 131072, true, false, true, false),
    (
        "z-ai/glm-4.5-air",
        "GLM 4.5 Air",
        131072,
        true,
        false,
        true,
        false,
    ),
    ("z-ai/glm-4.5v", "GLM 4.5V", 65536, true, false, true, false),
    ("z-ai/glm-4.6", "GLM 4.6", 204800, true, false, true, false),
    (
        "z-ai/glm-4.6v",
        "GLM 4.6V",
        131072,
        true,
        false,
        true,
        false,
    ),
    ("z-ai/glm-4.7", "GLM 4.7", 204800, true, false, true, false),
    (
        "z-ai/glm-4.7-flash",
        "GLM 4.7 Flash",
        202752,
        true,
        false,
        true,
        false,
    ),
    ("z-ai/glm-5", "GLM 5", 204800, true, false, true, false),
    (
        "z-ai/glm-5-turbo",
        "GLM 5 Turbo",
        202752,
        true,
        false,
        true,
        false,
    ),
    ("z-ai/glm-5.1", "GLM 5.1", 204800, true, false, true, false),
    ("z-ai/glm-5.2", "GLM 5.2", 1048576, true, true, true, false),
    (
        "z-ai/glm-5v-turbo",
        "GLM 5V Turbo",
        202752,
        true,
        false,
        true,
        false,
    ),
    (
        "~anthropic/claude-fable-latest",
        "Claude Fable Latest",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "~anthropic/claude-haiku-latest",
        "Anthropic Claude Haiku Latest",
        200000,
        true,
        false,
        true,
        false,
    ),
    (
        "~anthropic/claude-opus-latest",
        "Claude Opus Latest",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "~anthropic/claude-sonnet-latest",
        "Anthropic Claude Sonnet Latest",
        1000000,
        true,
        true,
        true,
        false,
    ),
    (
        "~google/gemini-flash-latest",
        "Google Gemini Flash Latest",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "~google/gemini-pro-latest",
        "Google Gemini Pro Latest",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "~moonshotai/kimi-latest",
        "MoonshotAI Kimi Latest",
        1048576,
        true,
        true,
        true,
        false,
    ),
    (
        "~openai/gpt-latest",
        "OpenAI GPT Latest",
        1050000,
        true,
        true,
        true,
        false,
    ),
    (
        "~openai/gpt-mini-latest",
        "OpenAI GPT Mini Latest",
        400000,
        true,
        true,
        true,
        false,
    ),
    (
        "~x-ai/grok-latest",
        "Grok Latest",
        500000,
        true,
        true,
        true,
        false,
    ),
];

/// Row lookup by exact id. Exact only, deliberately: a tier suffix changes the
/// context window, so a fuzzy match here would reintroduce the bug this table
/// exists to fix.
pub fn find(model_id: &str) -> Option<&'static OpenRouterModel> {
    OPENROUTER_MODELS.iter().find(|row| row.0 == model_id)
}

/// Does this OpenRouter model accept `reasoning: { effort }`?
pub fn takes_effort(model_id: &str) -> bool {
    find(model_id).map(|row| row.4).unwrap_or(false)
}

/// Can this model call tools? Unknown ids answer `true` — a model we have not
/// catalogued must not be blocked from a lane on our ignorance.
pub fn supports_tools(model_id: &str) -> bool {
    find(model_id).map(|row| row.5).unwrap_or(true)
}

/// Free-tier models only — the picker's default filter, since this project
/// runs on free lanes.
pub fn free_models() -> impl Iterator<Item = &'static OpenRouterModel> {
    OPENROUTER_MODELS.iter().filter(|row| row.6)
}
