//! Configuration file loader
//!
//! Loads config from the single Phoenix global config location:
//! `~/.phoenix/config.toml`

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

use super::*;

/// Configuration is human-authored control state, not a payload store. Keep a
/// deliberately small ceiling even though the shared private-file primitive
/// has a larger catch-all limit for other Phoenix state documents.
const MAX_CONFIG_BYTES: usize = 4 * 1024 * 1024;

pub struct ConfigLoader {
    paths: Vec<PathBuf>,
    force_path: Option<PathBuf>,
}

impl ConfigLoader {
    pub fn new() -> Self {
        Self {
            paths: Self::default_paths(),
            force_path: None,
        }
    }

    pub fn with_path(mut self, path: PathBuf) -> Self {
        self.force_path = Some(path);
        self
    }

    fn default_paths() -> Vec<PathBuf> {
        // Through phoenix_home() so PHOENIX_HOME isolates the WHOLE config
        // system, not just sessions/memory — a hardcoded ~/.phoenix here once
        // made a sandboxed `phoenix configure` edit the real user config.
        let global_config = crate::config::phoenix_home().join("config.toml");
        // Always retain the intended path. `exists()` follows symlinks and
        // turns a dangling/unsafe config symlink into the same benign-looking
        // state as a missing config. The bounded reader below distinguishes
        // those cases without following anything.
        vec![global_config]
    }

    pub fn load(&self) -> Result<PhoenixConfig> {
        let path = self
            .force_path
            .clone()
            .or_else(|| self.paths.first().cloned())
            .context("No config file found")?;

        self.load_from_file(&path)
    }

    fn load_from_file(&self, path: &Path) -> Result<PhoenixConfig> {
        // `with_path` intentionally accepts a config anywhere on disk (the
        // CLI's --config contract). The private reader also supports external
        // paths; it merely applies bounded, regular-file, no-symlink reads.
        // Lexically absolutize first so useful explicit paths such as
        // `./fixtures/config.toml` are not rejected for containing `.`.
        let read_path = absolute_lexical_path(path)?;
        let bytes = crate::config::private_io::read_private_file(&read_path)
            .with_context(|| format!("Failed to read config from {}", path.display()))?
            .with_context(|| format!("No config file found at {}", path.display()))?;
        if bytes.len() > MAX_CONFIG_BYTES {
            anyhow::bail!(
                "Config at {} is too large ({} bytes; max {MAX_CONFIG_BYTES})",
                path.display(),
                bytes.len()
            );
        }
        let contents = String::from_utf8(bytes)
            .with_context(|| format!("Config at {} is not valid UTF-8", path.display()))?;

        let toml_value: toml::Value = toml::from_str(&contents)
            .with_context(|| format!("Failed to parse config from {}", path.display()))?;

        let mut config = self.parse_toml(&toml_value)?;
        // Older `phoenix onboard` builds wrote `timeout_seconds = 300` into
        // every generated config even when the user never chose a provider
        // deadline. The long-work runtime now uses zero for that default, so
        // preserve compatibility for that exact generated value without
        // weakening hand-authored positive limits. New generated files write
        // zero directly.
        let generated_by_onboard = contents
            .lines()
            .any(|line| line.trim() == "# Generated by `phoenix onboard`");
        let persisted_timeout = toml_value
            .get("profile")
            .and_then(|profile| profile.get("llm"))
            .and_then(|llm| llm.get("timeout_seconds"))
            .and_then(toml::Value::as_integer);
        if generated_by_onboard && persisted_timeout == Some(300) {
            config.profile.llm.timeout_seconds = 0;
        }
        Ok(config)
    }

    fn parse_toml(&self, value: &toml::Value) -> Result<PhoenixConfig> {
        let mut profile = Profile::default();

        if let Some(tbl) = value.get("profile").and_then(|v| v.as_table()) {
            profile = self.parse_profile(tbl)?;
        } else if let Some(tbl) = value.get("llm").and_then(|v| v.as_table()) {
            profile.llm = self.parse_llm_profile(tbl)?;
        }

        if let Some(name) = value.get("profile_name").and_then(|v| v.as_str()) {
            profile.name = name.to_string();
        }

        Ok(PhoenixConfig { profile })
    }

    fn parse_profile(&self, tbl: &toml::map::Map<String, toml::Value>) -> Result<Profile> {
        let mut profile = Profile::default();

        if let Some(name) = tbl.get("name").and_then(|v| v.as_str()) {
            profile.name = name.to_string();
        }

        if let Some(llm) = tbl.get("llm").and_then(|v| v.as_table()) {
            profile.llm = self.parse_llm_profile(llm)?;
        }

        if let Some(search) = tbl.get("search").and_then(|v| v.as_table()) {
            profile.search = Some(self.parse_search_profile(search)?);
        }

        if let Some(crawl) = tbl.get("crawl").and_then(|v| v.as_table()) {
            profile.crawl = Some(self.parse_crawl_profile(crawl)?);
        }

        if let Some(scrape) = tbl.get("scrape").and_then(|v| v.as_table()) {
            profile.scrape = Some(self.parse_scrape_profile(scrape)?);
        }

        // Local MCP servers: `[[profile.mcp_server]]` array-of-tables.
        if let Some(servers) = tbl.get("mcp_server").and_then(|v| v.as_array()) {
            for entry in servers {
                if let Some(server_tbl) = entry.as_table() {
                    if let Some(server) = self.parse_mcp_server(server_tbl) {
                        profile.mcp_servers.push(server);
                    }
                }
            }
        }

        if let Some(web_fallback) = tbl.get("web_fallback").and_then(|v| v.as_table()) {
            profile.web_fallback = WebFallbackChains {
                search: toml_string_list(web_fallback.get("search")),
                crawl: toml_string_list(web_fallback.get("crawl")),
                scrape: toml_string_list(web_fallback.get("scrape")),
            };
        }

        if let Some(browser) = tbl.get("browser").and_then(|v| v.as_table()) {
            let mut b = crate::config::BrowserProfile::default();
            if let Some(s) = browser.get("source").and_then(|v| v.as_str()) {
                b.source = Some(s.to_string());
            }
            if let Some(value) = browser.get("attach_port") {
                let port = value
                    .as_integer()
                    .context("profile.browser.attach_port must be an integer")?;
                b.attach_port = Some(
                    u16::try_from(port)
                        .context("profile.browser.attach_port must be between 0 and 65535")?,
                );
            }
            if let Some(h) = browser.get("headless").and_then(|v| v.as_bool()) {
                b.headless = Some(h);
            }
            if let Some(path) = browser.get("binary").and_then(|v| v.as_str()) {
                b.binary = Some(path.to_string());
            }
            if let Some(args) = browser.get("extra_args").and_then(|v| v.as_array()) {
                b.extra_args = Some(
                    args.iter()
                        .filter_map(|a| a.as_str().map(str::to_string))
                        .collect(),
                );
            }
            if let Some(src) = browser.get("login_source").and_then(|v| v.as_str()) {
                b.login_source = Some(src.to_string());
            }
            if let Some(value) = browser.get("suspend_after_seconds") {
                let seconds = value
                    .as_integer()
                    .context("profile.browser.suspend_after_seconds must be an integer")?;
                let seconds = u64::try_from(seconds)
                    .context("profile.browser.suspend_after_seconds cannot be negative")?;
                anyhow::ensure!(
                    seconds == 0 || (60..=86_400).contains(&seconds),
                    "profile.browser.suspend_after_seconds must be 0 or 60..=86400"
                );
                b.suspend_after_seconds = Some(seconds);
            }
            profile.browser = Some(b);
        }

        Ok(profile)
    }

    fn parse_llm_profile(&self, tbl: &toml::map::Map<String, toml::Value>) -> Result<LLMProfile> {
        let mut profile = LLMProfile::default();

        if let Some(p) = tbl.get("provider").and_then(|v| v.as_str()) {
            profile.provider = p.to_string();
        }
        if let Some(m) = tbl.get("model").and_then(|v| v.as_str()) {
            profile.model = m.to_string();
        }
        if let Some(m) = tbl.get("orchestrator_model").and_then(|v| v.as_str()) {
            profile.orchestrator_model = Some(m.to_string());
        }
        if let Some(m) = tbl.get("specialist_model").and_then(|v| v.as_str()) {
            profile.specialist_model = Some(m.to_string());
        }
        if let Some(m) = tbl.get("librarian_model").and_then(|v| v.as_str()) {
            profile.librarian_model = Some(m.to_string());
        }
        if let Some(m) = tbl.get("vision_model").and_then(|v| v.as_str()) {
            profile.vision_model = Some(m.to_string());
        }
        if let Some(m) = tbl.get("vision_provider").and_then(|v| v.as_str()) {
            profile.vision_provider = Some(m.to_string());
        }
        if let Some(b) = tbl.get("native_vision").and_then(|v| v.as_bool()) {
            profile.native_vision = b;
        }
        if let Some(m) = tbl.get("image_model").and_then(|v| v.as_str()) {
            profile.image_model = Some(m.to_string());
        }
        if let Some(m) = tbl.get("image_provider").and_then(|v| v.as_str()) {
            profile.image_provider = Some(m.to_string());
        }
        if let Some(m) = tbl.get("specialist_provider").and_then(|v| v.as_str()) {
            profile.specialist_provider = Some(m.to_string());
        }
        if let Some(m) = tbl.get("librarian_provider").and_then(|v| v.as_str()) {
            profile.librarian_provider = Some(m.to_string());
        }
        if let Some(m) = tbl.get("memory_model").and_then(|v| v.as_str()) {
            profile.memory_model = Some(m.to_string());
        }
        if let Some(m) = tbl.get("memory_provider").and_then(|v| v.as_str()) {
            profile.memory_provider = Some(m.to_string());
        }
        for (key, slot) in [
            ("stt_model", &mut profile.stt_model),
            ("stt_provider", &mut profile.stt_provider),
            ("tts_model", &mut profile.tts_model),
            ("tts_provider", &mut profile.tts_provider),
            ("tts_voice", &mut profile.tts_voice),
            ("realtime_model", &mut profile.realtime_model),
            ("realtime_provider", &mut profile.realtime_provider),
            ("realtime_voice", &mut profile.realtime_voice),
        ] {
            if let Some(value) = tbl.get(key).and_then(|v| v.as_str()) {
                *slot = Some(value.to_string());
            }
        }
        if let Some(auth) = tbl.get("auth").and_then(|v| v.as_table()) {
            let mut auth_config = LLMAuthConfig::default();
            if let Some(method) = auth.get("method").and_then(|v| v.as_str()) {
                auth_config.method = Some(method.to_string());
            }
            if let Some(source) = auth.get("source").and_then(|v| v.as_str()) {
                auth_config.source = Some(source.to_string());
            }
            if let Some(profile_id) = auth.get("profile").and_then(|v| v.as_str()) {
                auth_config.profile = Some(profile_id.to_string());
            }
            if let Some(env_var) = auth.get("env_var").and_then(|v| v.as_str()) {
                auth_config.env_var = Some(env_var.to_string());
            }
            profile.auth = Some(auth_config);
        }
        if let Some(value) = tbl.get("temperature") {
            let temperature = value
                .as_float()
                .or_else(|| value.as_integer().map(|integer| integer as f64))
                .context("profile.llm.temperature must be numeric")?;
            let temperature = temperature as f32;
            if !temperature.is_finite() {
                anyhow::bail!("profile.llm.temperature is outside the supported numeric range");
            }
            profile.temperature = Some(temperature);
        }
        if let Some(value) = tbl.get("max_tokens") {
            let max_tokens = value
                .as_integer()
                .context("profile.llm.max_tokens must be an integer")?;
            profile.max_tokens = Some(
                u32::try_from(max_tokens)
                    .context("profile.llm.max_tokens must be a non-negative 32-bit value")?,
            );
        }
        if let Some(r) = tbl.get("reasoning_effort").and_then(|v| v.as_str()) {
            profile.reasoning_effort = Some(r.to_string());
        }
        if let Some(value) = tbl.get("context_window") {
            let context_window = value
                .as_integer()
                .context("profile.llm.context_window must be an integer")?;
            profile.context_window = Some(
                u64::try_from(context_window)
                    .context("profile.llm.context_window must be non-negative")?,
            );
        }
        if let Some(windows) = tbl.get("context_windows").and_then(|v| v.as_table()) {
            for (lane, value) in windows {
                let raw = value.as_integer().with_context(|| {
                    format!("profile.llm.context_windows.{lane} must be an integer")
                })?;
                let window = u64::try_from(raw).with_context(|| {
                    format!("profile.llm.context_windows.{lane} must be non-negative")
                })?;
                anyhow::ensure!(
                    window > 0,
                    "profile.llm.context_windows.{lane} must be greater than zero"
                );
                profile.context_windows.insert(lane.clone(), window);
            }
        }
        if let Some(value) = tbl.get("timeout_seconds") {
            let timeout = value
                .as_integer()
                .context("profile.llm.timeout_seconds must be an integer")?;
            profile.timeout_seconds = u64::try_from(timeout)
                .context("profile.llm.timeout_seconds must be non-negative")?;
        }
        // [profile.llm.efforts] — per-lane reasoning effort (role or agent
        // name → low/medium/high/xhigh). Missing lanes ride reasoning_effort.
        if let Some(efforts) = tbl.get("efforts").and_then(|v| v.as_table()) {
            profile.efforts = efforts
                .iter()
                .filter_map(|(lane, value)| {
                    value
                        .as_str()
                        .map(str::trim)
                        .filter(|e| !e.is_empty())
                        .map(|e| (lane.clone(), e.to_string()))
                })
                .collect();
        }
        // [profile.llm.agent_models] — individual-specialist primary models.
        if let Some(agent_models) = tbl.get("agent_models").and_then(|v| v.as_table()) {
            profile.agent_models = agent_models
                .iter()
                .filter_map(|(agent, value)| {
                    value
                        .as_str()
                        .map(str::trim)
                        .filter(|m| !m.is_empty())
                        .map(|m| (agent.clone(), m.to_string()))
                })
                .collect();
        }
        // [profile.llm.auth_by_lane] — WHICH stored account is a lane's
        // primary (role name or agent name → auth-profile id).
        if let Some(pins) = tbl.get("auth_by_lane").and_then(|v| v.as_table()) {
            profile.auth_by_lane = pins
                .iter()
                .filter_map(|(lane, value)| {
                    value
                        .as_str()
                        .map(str::trim)
                        .filter(|id| !id.is_empty())
                        .map(|id| (lane.clone(), id.to_string()))
                })
                .collect();
        }

        // Provider-specific native-compaction policy.  Older configs have no
        // table and therefore remain Phoenix-only.  Accept the short legacy
        // spelling too so hand-authored configs can use `[...compaction]`.
        let compaction_table = tbl
            .get("compaction_modes")
            .or_else(|| tbl.get("compaction"))
            .and_then(|v| v.as_table());
        if let Some(modes) = compaction_table {
            for (provider, value) in modes {
                let mode = value
                    .as_str()
                    .and_then(CompactionMode::parse)
                    .with_context(|| {
                        format!(
                            "profile.llm.compaction_modes.{provider} must be `phoenix_only` or `native_preferred`"
                        )
                    })?;
                profile.compaction_modes.insert(provider.clone(), mode);
            }
        }

        if let Some(fallback) = tbl.get("fallback").and_then(|v| v.as_table()) {
            profile.fallback = FallbackChains {
                orchestrator: toml_string_list(fallback.get("orchestrator")),
                specialist: toml_string_list(fallback.get("specialist")),
                librarian: toml_string_list(fallback.get("librarian")),
                vision: toml_string_list(fallback.get("vision")),
                image: toml_string_list(fallback.get("image")),
                agents: fallback
                    .get("agents")
                    .and_then(|v| v.as_table())
                    .map(|agents| {
                        agents
                            .iter()
                            .map(|(agent, chain)| (agent.clone(), toml_string_list(Some(chain))))
                            .filter(|(_, chain)| !chain.is_empty())
                            .collect()
                    })
                    .unwrap_or_default(),
            };
        }

        Ok(profile)
    }

    fn parse_search_profile(
        &self,
        tbl: &toml::map::Map<String, toml::Value>,
    ) -> Result<SearchProfile> {
        let provider = tbl
            .get("provider")
            .and_then(|v| v.as_str())
            .unwrap_or("duckduckgo");

        let search_provider = match provider {
            "google" => SearchProvider::Google,
            "bing" => SearchProvider::Bing,
            "serpapi" => SearchProvider::SerpAPI,
            "serper" => SearchProvider::Serper,
            "tavily" => SearchProvider::Tavily,
            "exa" => SearchProvider::Exa,
            "brave" | "brave-free" | "brave_search" => SearchProvider::Brave,
            "firecrawl" => SearchProvider::Firecrawl,
            "custom" => SearchProvider::Custom,
            _ => SearchProvider::DuckDuckGo,
        };

        let api_key = tbl
            .get("api_key")
            .and_then(|v| v.as_str())
            .map(String::from);
        let default_engine = tbl
            .get("default_engine")
            .and_then(|v| v.as_str())
            .unwrap_or("google")
            .to_string();
        let num_results = tbl
            .get("num_results")
            .and_then(|v| v.as_integer())
            .unwrap_or(10)
            .clamp(1, 20) as u32;
        let auth = tbl
            .get("auth")
            .and_then(|v| v.as_table())
            .map(|auth_tbl| self.parse_web_auth(auth_tbl));

        Ok(SearchProfile {
            provider: search_provider,
            api_key,
            auth,
            default_engine,
            num_results,
        })
    }

    fn parse_crawl_profile(
        &self,
        tbl: &toml::map::Map<String, toml::Value>,
    ) -> Result<CrawlProfile> {
        let provider = tbl
            .get("provider")
            .and_then(|v| v.as_str())
            .unwrap_or("firecrawl");

        let crawl_provider = match provider {
            "firecrawl" => CrawlProvider::Firecrawl,
            "tavily" => CrawlProvider::Tavily,
            "crawl4ai" => CrawlProvider::Crawl4AI,
            "scrapfly" => CrawlProvider::Scrapfly,
            "apify" => CrawlProvider::Apify,
            "custom" => CrawlProvider::Custom,
            _ => CrawlProvider::Firecrawl,
        };

        let api_key = tbl
            .get("api_key")
            .and_then(|v| v.as_str())
            .map(String::from);
        let auth = tbl
            .get("auth")
            .and_then(|v| v.as_table())
            .map(|auth_tbl| self.parse_web_auth(auth_tbl));
        let base_url = tbl
            .get("base_url")
            .and_then(|v| v.as_str())
            .map(String::from);
        let rate_limit = match tbl.get("rate_limit") {
            None => 10,
            Some(value) => {
                let value = value
                    .as_integer()
                    .context("profile.crawl.rate_limit must be an integer")?;
                u32::try_from(value)
                    .context("profile.crawl.rate_limit must be a non-negative 32-bit value")?
            }
        };

        Ok(CrawlProfile {
            provider: crawl_provider,
            api_key,
            auth,
            base_url,
            rate_limit,
        })
    }

    fn parse_scrape_profile(
        &self,
        tbl: &toml::map::Map<String, toml::Value>,
    ) -> Result<ScrapeProfile> {
        let provider = tbl
            .get("provider")
            .and_then(|v| v.as_str())
            .unwrap_or("firecrawl");

        let scrape_provider = match provider {
            "firecrawl" => ScrapeProvider::Firecrawl,
            "tavily" => ScrapeProvider::Tavily,
            "scraperapi" => ScrapeProvider::ScraperAPI,
            "scrapingbee" => ScrapeProvider::ScrapingBee,
            "custom" => ScrapeProvider::Custom,
            _ => ScrapeProvider::Firecrawl,
        };

        let api_key = tbl
            .get("api_key")
            .and_then(|v| v.as_str())
            .map(String::from);
        let auth = tbl
            .get("auth")
            .and_then(|v| v.as_table())
            .map(|auth_tbl| self.parse_web_auth(auth_tbl));
        let base_url = tbl
            .get("base_url")
            .and_then(|v| v.as_str())
            .map(String::from);

        Ok(ScrapeProfile {
            provider: scrape_provider,
            api_key,
            auth,
            base_url,
        })
    }

    /// One `[[profile.mcp_server]]` entry. Needs a `command` (local stdio) or
    /// a `url` (remote HTTP) — an entry with neither is dropped; everything
    /// else defaults sanely. `bearer = "…"` is sugar for an Authorization
    /// header on remote servers.
    fn parse_mcp_server(
        &self,
        tbl: &toml::map::Map<String, toml::Value>,
    ) -> Option<McpServerConfig> {
        let command = tbl
            .get("command")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .trim()
            .to_string();
        let url = tbl
            .get("url")
            .and_then(|v| v.as_str())
            .map(str::trim)
            .filter(|u| !u.is_empty())
            .map(String::from);
        if command.is_empty() && url.is_none() {
            return None;
        }
        let name = tbl
            .get("name")
            .and_then(|v| v.as_str())
            .or(url.as_deref())
            .unwrap_or(&command)
            .to_string();
        let args = toml_string_list(tbl.get("args"));
        let string_map = |key: &str| -> std::collections::BTreeMap<String, String> {
            tbl.get(key)
                .and_then(|v| v.as_table())
                .map(|map_tbl| {
                    map_tbl
                        .iter()
                        .filter_map(|(k, v)| v.as_str().map(|s| (k.clone(), s.to_string())))
                        .collect()
                })
                .unwrap_or_default()
        };
        let env = string_map("env");
        let mut headers = string_map("headers");
        if let Some(bearer) = tbl.get("bearer").and_then(|v| v.as_str()) {
            if !bearer.trim().is_empty() {
                headers
                    .entry("Authorization".to_string())
                    .or_insert_with(|| format!("Bearer {}", bearer.trim()));
            }
        }
        Some(McpServerConfig {
            name,
            command,
            args,
            cwd: tbl.get("cwd").and_then(|v| v.as_str()).map(String::from),
            env,
            url,
            headers,
            route: tbl.get("route").and_then(|v| v.as_str()).map(String::from),
            // Default ON: listing a server IS opting in. `enabled = false`
            // parks one without deleting it.
            enabled: tbl.get("enabled").and_then(|v| v.as_bool()).unwrap_or(true),
            description: tbl
                .get("description")
                .and_then(|v| v.as_str())
                .map(String::from),
        })
    }

    fn parse_web_auth(&self, tbl: &toml::map::Map<String, toml::Value>) -> WebAuthConfig {
        WebAuthConfig {
            source: tbl.get("source").and_then(|v| v.as_str()).map(String::from),
            profile: tbl
                .get("profile")
                .and_then(|v| v.as_str())
                .map(String::from),
            env_var: tbl
                .get("env_var")
                .and_then(|v| v.as_str())
                .map(String::from),
        }
    }
}

/// Normalize `.`/`..` without resolving filesystem symlinks. Canonicalizing
/// would follow the very symlink the bounded private reader is meant to
/// reject, while passing a relative `./path` through unchanged would reject a
/// legitimate explicit CLI config path on path-shape grounds.
fn absolute_lexical_path(path: &Path) -> Result<PathBuf> {
    use std::path::Component;

    let joined = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .context("Failed to resolve the current directory for config loading")?
            .join(path)
    };
    let mut normalized = PathBuf::new();
    for component in joined.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                // `joined` is absolute, so a parent at the filesystem root is
                // simply clamped there, matching ordinary path traversal.
                normalized.pop();
            }
            other => normalized.push(other.as_os_str()),
        }
    }
    Ok(normalized)
}

impl Default for ConfigLoader {
    fn default() -> Self {
        Self::new()
    }
}

/// A TOML array of strings → Vec<String> (missing / wrong type = empty).
fn toml_string_list(value: Option<&toml::Value>) -> Vec<String> {
    value
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|item| item.as_str())
                .map(str::to_string)
                .collect()
        })
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(contents: &str) -> PhoenixConfig {
        let value: toml::Value = toml::from_str(contents).expect("valid toml");
        ConfigLoader::new().parse_toml(&value).expect("parses")
    }

    const BASE: &str =
        "[profile]\nname = \"t\"\n[profile.llm]\nprovider = \"ollama\"\nmodel = \"m\"\n";

    #[test]
    fn old_onboard_timeout_default_migrates_without_overriding_authored_limits() {
        let root = tempfile::tempdir().unwrap();
        let generated = root.path().join("generated.toml");
        std::fs::write(
            &generated,
            format!("# Phoenix configuration\n# Generated by `phoenix onboard`\n{BASE}timeout_seconds = 300\n"),
        )
        .unwrap();
        let loaded = ConfigLoader::new().with_path(generated).load().unwrap();
        assert_eq!(loaded.profile.llm.timeout_seconds, 0);

        let authored = root.path().join("authored.toml");
        std::fs::write(&authored, format!("{BASE}timeout_seconds = 300\n")).unwrap();
        let loaded = ConfigLoader::new().with_path(authored).load().unwrap();
        assert_eq!(loaded.profile.llm.timeout_seconds, 300);

        let generated_explicit = root.path().join("generated-explicit.toml");
        std::fs::write(
            &generated_explicit,
            format!("# Phoenix configuration\n# Generated by `phoenix onboard`\n{BASE}timeout_seconds = 120\n"),
        )
        .unwrap();
        let loaded = ConfigLoader::new()
            .with_path(generated_explicit)
            .load()
            .unwrap();
        assert_eq!(loaded.profile.llm.timeout_seconds, 120);
    }

    #[test]
    fn native_vision_defaults_to_pixels_and_respects_explicit_opt_out() {
        assert!(parse(BASE).profile.llm.native_vision);
        assert!(LLMProfile::new("openai-codex", "gpt-5.6-sol").native_vision);
        assert!(!parse(&format!("{BASE}native_vision = false\n")).profile.llm.native_vision);
        assert!(parse(&format!("{BASE}native_vision = true\n")).profile.llm.native_vision);
    }

    #[test]
    fn browser_idle_suspension_is_bounded_and_zero_can_disable_it() {
        let cfg = parse(&format!(
            "{BASE}\n[profile.browser]\nsource = \"phoenix\"\nsuspend_after_seconds = 600\n"
        ));
        assert_eq!(
            cfg.profile.browser.unwrap().suspend_after_seconds,
            Some(600)
        );
        let disabled = parse(&format!(
            "{BASE}\n[profile.browser]\nsource = \"phoenix\"\nsuspend_after_seconds = 0\n"
        ));
        assert_eq!(
            disabled.profile.browser.unwrap().suspend_after_seconds,
            Some(0)
        );
        for invalid in [1, 59, 86_401] {
            let value: toml::Value = toml::from_str(&format!(
                "{BASE}\n[profile.browser]\nsource = \"phoenix\"\nsuspend_after_seconds = {invalid}\n"
            ))
            .unwrap();
            assert!(ConfigLoader::new().parse_toml(&value).is_err());
        }
    }

    #[test]
    fn mcp_server_remote_url_with_bearer_and_headers() {
        let cfg = parse(&format!(
            "{BASE}\n[[profile.mcp_server]]\nname = \"ctx\"\nurl = \"https://example.com/mcp\"\nbearer = \"tok123\"\nheaders = {{ \"X-Extra\" = \"1\" }}\n"
        ));
        let server = &cfg.profile.mcp_servers[0];
        assert!(server.is_remote());
        assert_eq!(server.url.as_deref(), Some("https://example.com/mcp"));
        assert_eq!(
            server.headers.get("Authorization").map(String::as_str),
            Some("Bearer tok123")
        );
        assert_eq!(server.headers.get("X-Extra").map(String::as_str), Some("1"));
    }

    #[test]
    fn auth_by_lane_pins_which_account_is_a_lanes_primary() {
        // Without this table, a provider holding several accounts resolves its
        // primary alphabetically — `nvidia:2` always beat `nvidia:6`, which is
        // an ASCII accident, not a choice.
        let cfg = parse(&format!(
            "{BASE}\n[profile.llm.auth_by_lane]\norchestrator = \"nvidia:4\"\ncoder = \" nvidia:6 \"\nblank = \"\"\n"
        ));
        let llm = &cfg.profile.llm;
        assert_eq!(
            llm.auth_by_lane.get("orchestrator").map(String::as_str),
            Some("nvidia:4")
        );
        assert_eq!(
            llm.auth_by_lane.get("coder").map(String::as_str),
            Some("nvidia:6")
        );
        // An empty value is not a pin.
        assert!(!llm.auth_by_lane.contains_key("blank"));
        // The pin only applies to the provider that owns the account…
        assert_eq!(llm.lane_pin("orchestrator", "nvidia"), Some("nvidia:4"));
        // …a stale pin left behind by a provider switch is ignored, never fatal.
        assert_eq!(llm.lane_pin("orchestrator", "openai-codex"), None);
        // xai ≅ grok-cli share one credential family.
        let kin = parse(&format!(
            "{BASE}\n[profile.llm.auth_by_lane]\nspecialist = \"xai:2\"\n"
        ));
        assert_eq!(
            kin.profile.llm.lane_pin("specialist", "grok-cli"),
            Some("xai:2")
        );
        // A lane with no pin resolves the way it always did.
        assert_eq!(llm.lane_pin("librarian", "nvidia"), None);
    }

    #[test]
    fn with_lane_pin_declares_the_account_as_the_auth_source() {
        let cfg = parse(&format!(
            "{BASE}\n[profile.llm.auth_by_lane]\nspecialist = \"nvidia:6\"\n"
        ));
        let pinned = cfg.profile.llm.with_lane_pin("specialist", "nvidia");
        let auth = pinned.auth.as_ref().expect("pin declares auth");
        assert_eq!(auth.source.as_deref(), Some("profile"));
        assert_eq!(auth.profile.as_deref(), Some("nvidia:6"));
        // No pin for this lane/provider pair → the profile is untouched, so
        // resolution falls through env vars then the provider's own accounts.
        let untouched = cfg.profile.llm.with_lane_pin("librarian", "nvidia");
        assert!(untouched.auth.is_none());
        let wrong_provider = cfg.profile.llm.with_lane_pin("specialist", "groq");
        assert!(wrong_provider.auth.is_none());
    }

    #[test]
    fn mcp_server_needs_command_or_url() {
        let cfg = parse(&format!(
            "{BASE}\n[[profile.mcp_server]]\nname = \"empty\"\n\n[[profile.mcp_server]]\nname = \"local\"\ncommand = \"t3mp3st\"\n"
        ));
        let names: Vec<&str> = cfg
            .profile
            .mcp_servers
            .iter()
            .map(|s| s.name.as_str())
            .collect();
        assert_eq!(names, vec!["local"]);
        assert!(!cfg.profile.mcp_servers[0].is_remote());
    }

    #[test]
    fn negative_unsigned_config_values_are_rejected_instead_of_wrapping() {
        for document in [
            format!("{BASE}max_tokens = -1\n"),
            format!("{BASE}context_window = -1\n"),
            format!("{BASE}timeout_seconds = -1\n"),
        ] {
            let value: toml::Value = toml::from_str(&document).unwrap();
            assert!(ConfigLoader::new().parse_toml(&value).is_err());
        }
    }

    #[test]
    fn explicit_external_config_path_still_loads() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("outside-phoenix.toml");
        std::fs::write(&path, BASE).unwrap();

        let config = ConfigLoader::new().with_path(path).load().unwrap();
        assert_eq!(config.profile.llm.provider, "ollama");
        assert_eq!(config.profile.llm.model, "m");
    }

    #[test]
    fn explicit_relative_path_is_lexically_normalized_without_canonicalizing() {
        let normalized = absolute_lexical_path(Path::new("./one/../config.toml")).unwrap();
        assert!(normalized.is_absolute());
        assert_eq!(
            normalized.file_name().and_then(|name| name.to_str()),
            Some("config.toml")
        );
        assert!(!normalized.components().any(|component| matches!(
            component,
            std::path::Component::CurDir | std::path::Component::ParentDir
        )));
    }

    #[test]
    fn invalid_utf8_config_is_an_error_not_an_empty_default() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(&path, [0xff, 0xfe]).unwrap();

        let error = ConfigLoader::new()
            .with_path(path)
            .load()
            .err()
            .expect("invalid UTF-8 must fail")
            .to_string();
        assert!(error.contains("valid UTF-8"), "{error}");
    }

    #[test]
    fn oversized_config_is_rejected_before_toml_parsing() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        let file = std::fs::File::create(&path).unwrap();
        file.set_len(MAX_CONFIG_BYTES as u64 + 1).unwrap();

        let error = ConfigLoader::new()
            .with_path(path)
            .load()
            .err()
            .expect("oversized config must fail")
            .to_string();
        assert!(error.contains("too large"), "{error}");
    }

    #[cfg(unix)]
    #[test]
    fn symlinked_config_is_rejected() {
        use std::os::unix::fs::symlink;

        let dir = tempfile::tempdir().unwrap();
        let target = dir.path().join("real.toml");
        let linked = dir.path().join("config.toml");
        std::fs::write(&target, BASE).unwrap();
        symlink(&target, &linked).unwrap();

        assert!(ConfigLoader::new().with_path(linked).load().is_err());
    }

    #[cfg(unix)]
    #[test]
    fn fifo_config_is_rejected_without_opening_it_blocking() {
        use std::ffi::CString;
        use std::os::unix::ffi::OsStrExt;

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        let c_path = CString::new(path.as_os_str().as_bytes()).unwrap();
        assert_eq!(unsafe { libc::mkfifo(c_path.as_ptr(), 0o600) }, 0);

        assert!(ConfigLoader::new().with_path(path).load().is_err());
    }
}
